# Generated by Django 5.1.15 on 2026-09-02 01:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_role_is_account_admin'),
        ('inbound_nfe', '0003_supplieritemmapping_confidence_and_more'),
        ('menu', '0003_product_allow_negative_stock_product_brand_and_more'),
        ('restaurants', '0002_command_current_table_commandmovementlog'),
        ('stock', '0002_alter_stocklocation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('asset_code', models.CharField(db_index=True, help_text='Código patrimonial interno (ex: EQ-000001).', max_length=40)),
                ('supplier_cnpj', models.CharField(blank=True, max_length=14)),
                ('supplier_name', models.CharField(blank=True, max_length=180)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('serial_number', models.CharField(blank=True, db_index=True, help_text='Número de série de fábrica.', max_length=120)),
                ('patrimony_number', models.CharField(blank=True, help_text='Número de plaqueta física adicional.', max_length=60)),
                ('manufacturer_code', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('IN_STOCK', 'Em Estoque / Aguardando Instalação'), ('IN_USE', 'Em Uso / Operação'), ('IN_MAINTENANCE', 'Em Manutenção'), ('BROKEN', 'Com Avaria / Inoperante'), ('LOANED', 'Emprestado / Comodato'), ('TRANSFERRED', 'Transferido'), ('INACTIVE', 'Desativado'), ('DISPOSED', 'Baixado / Descartado'), ('LOST', 'Extraviado'), ('STOLEN', 'Furtado / Roubado')], db_index=True, default='IN_USE', max_length=25)),
                ('warranty_start_date', models.DateField(blank=True, null=True)),
                ('warranty_end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('warranty_months', models.PositiveIntegerField(default=12)),
                ('warranty_provider', models.CharField(blank=True, max_length=180)),
                ('warranty_terms', models.TextField(blank=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('useful_life_months', models.PositiveIntegerField(blank=True, null=True)),
                ('qr_code_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(help_text='Localização física atual do equipamento.', on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='stock.stocklocation')),
                ('nfe', models.ForeignKey(blank=True, help_text='NF-e de compra de origem.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='inbound_nfe.inboundnfe')),
                ('nfe_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='inbound_nfe.inboundnfeitem')),
                ('product', models.ForeignKey(help_text='Produto mestre correspondente.', on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='menu.product')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='stock.goodsreceipt')),
                ('responsible_person', models.ForeignKey(blank=True, help_text='Colaborador responsável pelo ativo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_assets', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.restaurant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ativo Patrimonial',
                'verbose_name_plural': 'Ativos Patrimoniais',
                'ordering': ['asset_code'],
            },
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('disposal_type', models.CharField(choices=[('SCRAPPED', 'Sucata / Descarte'), ('SOLD', 'Vendido'), ('DONATED', 'Doado'), ('LOST', 'Extraviado'), ('STOLEN', 'Furtado / Roubado'), ('IRREPARABLE', 'Sem Reparo / Danificado'), ('OTHER', 'Outro')], default='SCRAPPED', max_length=25)),
                ('disposed_at', models.DateTimeField(auto_now_add=True)),
                ('sale_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disposal', to='assets.asset')),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorized_asset_disposals', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.restaurant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Baixa Patrimonial',
                'verbose_name_plural': 'Baixas Patrimoniais',
                'ordering': ['-disposed_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetLocationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='assets.asset')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_transferred_from', to='stock.stocklocation')),
                ('moved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.restaurant')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_transferred_to', to='stock.stocklocation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Localização do Ativo',
                'verbose_name_plural': 'Históricos de Localizações dos Ativos',
                'ordering': ['-moved_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('account', 'asset_code'), name='unique_asset_code_by_account'),
        ),
    ]
