# Generated by Django 5.1.15 on 2026-09-04 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('inbound_nfe', '0008_inboundnfe_cancellation_event_nsu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='source_nfe_cancellation_event',
            field=models.ForeignKey(blank=True, help_text='Evento de cancelamento da NF-e que gerou esta inconsistência patrimonial.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affected_assets', to='inbound_nfe.nfeevent'),
        ),
        migrations.AddField(
            model_name='asset',
            name='source_nfe_cancelled',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica se a NF-e de compra que originou este ativo foi cancelada na SEFAZ.'),
        ),
    ]
