# Generated by Django 5.1.15 on 2026-10-01 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_local_fiscal_allowed'),
        ('assets', '0002_asset_source_nfe_cancellation_event_and_more'),
        ('inbound_nfe', '0010_reativa_insumos_presos_a_nfe'),
        ('menu', '0011_preco_base_do_produto'),
        ('restaurants', '0009_campos_adicionais_e_codigo_do_operador'),
        ('stock', '0007_alter_stockmovement_movement_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asset',
            name='unique_asset_code_by_account',
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('account', 'asset_code'), name='unique_asset_code_by_account'),
        ),
    ]
