# Generated by Django 5.1.15 on 2026-08-03 19:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('menu', '0001_initial'),
        ('orders', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('driver_type', models.CharField(choices=[('browser', 'Browser'), ('escpos', 'ESC/POS')], default='browser', max_length=24)),
                ('connection_type', models.CharField(choices=[('windows', 'Windows / USB'), ('network', 'TCP/IP'), ('serial', 'Serial')], default='windows', max_length=16)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('host', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.PositiveIntegerField(default=9100)),
                ('timeout_seconds', models.PositiveIntegerField(default=10)),
                ('auto_print', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.restaurant')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printers', to='restaurants.tablesector')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('job_type', models.CharField(db_index=True, default='receipt', max_length=32)),
                ('status', models.CharField(db_index=True, default='rendered', max_length=24)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('html_content', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='orders.order')),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to=settings.AUTH_USER_MODEL)),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='printers.printer')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.restaurant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('protocol', models.CharField(choices=[('generic', 'Generico'), ('toledo_prt2', 'Toledo PRT2'), ('filizola', 'Filizola'), ('urano', 'Urano')], default='generic', max_length=24)),
                ('port', models.CharField(blank=True, help_text='Porta usada pelo agente local, ex.: COM3 ou /dev/ttyUSB0.', max_length=64)),
                ('reading_max_age_seconds', models.PositiveIntegerField(default=120, help_text='Idade maxima de uma leitura para ser aceita em um pedido.')),
                ('auto_print', models.BooleanField(default=False)),
                ('auto_print_delay_seconds', models.PositiveIntegerField(default=3, help_text='Segundos que a balanca deve ficar estavel antes de imprimir (aplicado pelo agente).')),
                ('agent_instance_id', models.CharField(blank=True, help_text='Identificador do PDV Desktop que possui a leitura exclusiva da balanca.', max_length=120)),
                ('agent_lease_expires_at', models.DateTimeField(blank=True, help_text='Validade da posse exclusiva da balanca pelo agente local.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('active_order', models.ForeignKey(blank=True, help_text='Pedido corrente vinculado a balanca (usado no gatilho automatico).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_scales', to='orders.order')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('printer', models.ForeignKey(blank=True, help_text='Impressora onde a nota de pesagem sera impressa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scales', to='printers.printer')),
                ('product', models.ForeignKey(blank=True, help_text='Produto por kilo usado para precificar a pesagem.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scales', to='menu.product')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.restaurant')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scales', to='restaurants.tablesector')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScaleReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=9)),
                ('tare_kg', models.DecimalField(decimal_places=3, default=0, max_digits=9)),
                ('is_stable', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('agent', 'Agente local'), ('manual', 'Digitacao manual')], default='agent', max_length=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(blank=True, help_text='Preenchido quando a leitura vira um item de pedido.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scale_readings', to='orders.orderitem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.restaurant')),
                ('scale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='printers.scale')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='printer',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='unique_printer_by_branch'),
        ),
        migrations.AddIndex(
            model_name='printjob',
            index=models.Index(fields=['branch', 'job_type', 'status', 'created_at'], name='printers_pr_branch__886e9f_idx'),
        ),
        migrations.AddConstraint(
            model_name='scale',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='unique_scale_by_branch'),
        ),
        migrations.AddIndex(
            model_name='scalereading',
            index=models.Index(fields=['scale', 'created_at'], name='printers_sc_scale_i_4e592f_idx'),
        ),
    ]
