# Generated by Django 5.1.15 on 2026-07-22 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0001_initial'),
        ('restaurants', '0002_alter_restaurant_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='scale',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scales', to='restaurants.tablesector'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printers', to='restaurants.tablesector'),
        ),
    ]
