# Generated by Django 5.1.15 on 2026-09-19 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0003_print_dispatch_and_cancellation'),
        ('restaurants', '0006_restaurant_commands_per_table_and_grace'),
    ]

    operations = [
        migrations.AddField(
            model_name='scale',
            name='active_command',
            field=models.ForeignKey(blank=True, help_text='Comanda que acabou de passar o cartao nesta balanca.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_scales', to='restaurants.command'),
        ),
        migrations.AddField(
            model_name='scale',
            name='active_command_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scale',
            name='command_binding_seconds',
            field=models.PositiveIntegerField(default=60, help_text='Validade do vinculo com a comanda depois da leitura do cartao.'),
        ),
        migrations.AddField(
            model_name='scale',
            name='weighing_mode',
            field=models.CharField(choices=[('counter', 'Balcao (pedido avulso por pesagem)'), ('command', 'Comanda (o cliente passa o cartao antes de pesar)')], default='counter', max_length=16),
        ),
    ]
