# Generated by Django 5.1.15 on 2026-09-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0004_scale_active_command_scale_active_command_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scalereading',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
