# Generated by Django 5.1.15 on 2026-09-20 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitem_command_commandbatch_commanditem_and_more'),
        ('printers', '0005_scalereading_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='scalereading',
            name='command_item',
            field=models.ForeignKey(blank=True, help_text='Preenchido quando a leitura vira uma anotação na comanda.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scale_readings', to='orders.commanditem'),
        ),
    ]
