# Generated by Django 5.1.15 on 2026-09-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0006_scalereading_command_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='cash_drawer_enabled',
            field=models.BooleanField(default=False, help_text='Abre a gaveta ligada a esta impressora ao imprimir venda em dinheiro e documentos de caixa.'),
        ),
        migrations.AddField(
            model_name='printer',
            name='cash_drawer_off_ms',
            field=models.PositiveSmallIntegerField(default=400, help_text='Intervalo desligado depois do pulso. Deve ser maior que o tempo ligado.'),
        ),
        migrations.AddField(
            model_name='printer',
            name='cash_drawer_on_ms',
            field=models.PositiveSmallIntegerField(default=100, help_text='Tempo com a bobina energizada. Comece por 100 ms: pulso curto demais nao destrava, longo demais aquece a bobina.'),
        ),
        migrations.AddField(
            model_name='printer',
            name='cash_drawer_pin',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Pino 2 (primeira gaveta)'), (5, 'Pino 5 (segunda gaveta)')], default=2, help_text='Saida do conector RJ12 acionada. A primeira gaveta costuma ser o pino 2.'),
        ),
    ]
