# Generated by Django 5.1.15 on 2026-10-01 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_local_fiscal_allowed'),
        ('menu', '0012_unico_so_entre_ativos'),
        ('orders', '0013_campos_adicionais_e_codigo_do_operador'),
        ('printers', '0009_cash_drawer_follows_the_driver'),
        ('restaurants', '0009_campos_adicionais_e_codigo_do_operador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='printer',
            name='unique_printer_by_branch',
        ),
        migrations.RemoveConstraint(
            model_name='scale',
            name='unique_scale_by_branch',
        ),
        migrations.AddConstraint(
            model_name='printer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('branch', 'name'), name='unique_printer_by_branch'),
        ),
        migrations.AddConstraint(
            model_name='scale',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('branch', 'name'), name='unique_scale_by_branch'),
        ),
    ]
