# Generated by Django 5.1.15 on 2026-08-30 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_cosmosconfig'),
        ('menu', '0003_product_stock_consumption_quantity_and_more'),
        ('orders', '0004_kitchen_dispatch_grace_period'),
        ('restaurants', '0003_hash_plain_cash_action_passwords'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='stock.stockmovement'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source_key',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('adjustment', 'Adjustment'), ('sale', 'Sale'), ('inventory', 'Inventory'), ('reversal', 'Reversal')], db_index=True, max_length=24),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('source_key', ''), _negated=True), ('deleted_at__isnull', True)), fields=('account', 'source_key'), name='unique_stock_movement_source_key'),
        ),
    ]
