# Generated by Django 5.1.15 on 2026-09-02 01:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_is_account_admin'),
        ('inbound_nfe', '0003_supplieritemmapping_confidence_and_more'),
        ('menu', '0003_product_allow_negative_stock_product_brand_and_more'),
        ('orders', '0004_kitchen_dispatch_grace_period'),
        ('restaurants', '0002_command_current_table_commandmovementlog'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocklocation',
            options={'verbose_name': 'Local de Estoque', 'verbose_name_plural': 'Locais de Estoque'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Movimento de Estoque', 'verbose_name_plural': 'Movimentos de Estoque'},
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='location_type',
            field=models.CharField(choices=[('STORAGE', 'Estoque Central / Depósito'), ('KITCHEN', 'Cozinha'), ('BAR', 'Bar / Balcão'), ('MAINTENANCE', 'Manutenção'), ('DISPOSAL', 'Descarte'), ('OTHER', 'Outro')], default='STORAGE', help_text='Tipo operacional do local de armazenamento.', max_length=20),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='parent_location',
            field=models.ForeignKey(blank=True, help_text='Local pai para hierarquia (ex: Freezer 1 dentro da Cozinha).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='stock.stocklocation'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='stock.stocklocation'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='nfe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inbound_nfe.inboundnfe'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='nfe_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inbound_nfe.inboundnfeitem'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='menu.product'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='stock.stocklocation'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_unit',
            field=models.CharField(default='UN', max_length=12),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='menu.ingredient'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('PURCHASE_ENTRY', 'Entrada por Compra (NF-e)'), ('SALE_OUTPUT', 'Saída por Venda'), ('PRODUCTION_CONSUMPTION', 'Consumo em Ficha Técnica'), ('TRANSFER_IN', 'Transferência (Entrada)'), ('TRANSFER_OUT', 'Transferência (Saída)'), ('LOSS', 'Perda / Desperdício'), ('BREAKAGE', 'Quebra de Reutilizável / Utensílio'), ('EXPIRATION', 'Baixa por Validade Vencida'), ('RETURN_TO_SUPPLIER', 'Devolução ao Fornecedor'), ('CUSTOMER_RETURN', 'Retorno de Cliente'), ('INVENTORY_ADJUSTMENT_POSITIVE', 'Ajuste de Inventário (+)'), ('INVENTORY_ADJUSTMENT_NEGATIVE', 'Ajuste de Inventário (-)'), ('INITIAL_BALANCE', 'Implantação de Saldo'), ('ASSET_DISPOSAL', 'Baixa Patrimonial'), ('in', 'Entrada (Legado)'), ('out', 'Saída (Legado)'), ('adjustment', 'Ajuste (Legado)'), ('sale', 'Venda (Legado)'), ('inventory', 'Inventário (Legado)')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=4, help_text='Quantidade movimentada (positiva para entradas, negativa/positiva conforme tipo).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, help_text='Identificador único da conferência (ex: REC-000045).', max_length=40)),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora física do recebimento.')),
                ('status', models.CharField(choices=[('DRAFT', 'Em Conferência'), ('CONFIRMED', 'Confirmado'), ('DIVERGENT', 'Confirmado com Divergência'), ('CANCELLED', 'Cancelado')], db_index=True, default='CONFIRMED', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Observações gerais da conferência e recebimento.')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, help_text='NF-e de origem da mercadoria.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='inbound_nfe.inboundnfe')),
                ('received_by', models.ForeignKey(help_text='Usuário/conferente que realizou o recebimento.', on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.restaurant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recebimento de Mercadorias',
                'verbose_name_plural': 'Recebimentos de Mercadorias',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='stock.goodsreceipt'),
        ),
        migrations.CreateModel(
            name='GoodsReceiptItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('expected_quantity', models.DecimalField(decimal_places=4, default=0, help_text='Quantidade declarada na NF-e convertida para a unidade de estoque.', max_digits=18)),
                ('received_quantity', models.DecimalField(decimal_places=4, default=0, help_text='Quantidade física conferida/pesada no recebimento.', max_digits=18)),
                ('difference_quantity', models.DecimalField(decimal_places=4, default=0, help_text='Divergência: recebido - esperado.', max_digits=18)),
                ('accepted_quantity', models.DecimalField(decimal_places=4, default=0, help_text='Quantidade efetivamente aceita para estoque.', max_digits=18)),
                ('rejected_quantity', models.DecimalField(decimal_places=4, default=0, help_text='Quantidade rejeitada/devolvida ao fornecedor.', max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, help_text='Custo unitário real da mercadoria recebida.', max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('lot_number', models.CharField(blank=True, help_text='Número do lote do fabricante/fornecedor.', max_length=60)),
                ('manufacturing_date', models.DateField(blank=True, help_text='Data de fabricação do lote.', null=True)),
                ('expiration_date', models.DateField(blank=True, help_text='Data de validade do lote.', null=True)),
                ('serials', models.JSONField(blank=True, default=list, help_text='Lista de números de série gerados para itens patrimoniais.')),
                ('notes', models.TextField(blank=True, help_text='Motivo da divergência ou observações do item.')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('nfe_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_items', to='inbound_nfe.inboundnfeitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='menu.product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.goodsreceipt')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.restaurant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item de Recebimento',
                'verbose_name_plural': 'Itens de Recebimento',
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='receipt_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='stock.goodsreceiptitem'),
        ),
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('lot_number', models.CharField(db_index=True, help_text='Número ou identificador do lote.', max_length=60)),
                ('supplier_cnpj', models.CharField(blank=True, max_length=14)),
                ('supplier_name', models.CharField(blank=True, max_length=180)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, db_index=True, help_text='Data de validade para controle FEFO.', null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('initial_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('available_quantity', models.DecimalField(db_index=True, decimal_places=4, default=0, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo / Disponível'), ('CONSUMED', 'Esgotado'), ('EXPIRED', 'Vencido'), ('BLOCKED', 'Bloqueado / Quarentena'), ('DISCARDED', 'Descartado')], db_index=True, default='ACTIVE', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='stock.stocklocation')),
                ('nfe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_lots', to='inbound_nfe.inboundnfe')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lots', to='menu.product')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_lots', to='stock.goodsreceipt')),
                ('receipt_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_lots', to='stock.goodsreceiptitem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.restaurant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de Estoque',
                'verbose_name_plural': 'Lotes de Estoque',
                'ordering': ['expiration_date', 'received_at'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='inventory_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='stock.inventorylot'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['branch', 'product', 'created_at'], name='stock_stock_branch__ede6fe_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylot',
            index=models.Index(fields=['branch', 'product', 'status', 'expiration_date'], name='stock_inven_branch__0bc205_idx'),
        ),
    ]
