# Generated by Django 5.1.15 on 2026-09-04 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stocklocation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Local de estoque de entrada.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='stock.stocklocation'),
        ),
    ]
