# Generated by Django 5.1.15 on 2026-09-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stockmovement_original_movement_and_more'),
        ('stock', '0005_stock_settings_account_scoped'),
    ]

    operations = [
    ]
