# Generated by Django 5.1.15 on 2026-09-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_merge_20260919_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('reversal', 'Reversal (Legado)'), ('PURCHASE_ENTRY', 'Entrada por Compra (NF-e)'), ('NFE_CANCELLATION_REVERSAL', 'Estorno por Cancelamento de NF-e'), ('SALE_OUTPUT', 'Saída por Venda'), ('PRODUCTION_CONSUMPTION', 'Consumo em Ficha Técnica'), ('TRANSFER_IN', 'Transferência (Entrada)'), ('TRANSFER_OUT', 'Transferência (Saída)'), ('LOSS', 'Perda / Desperdício'), ('BREAKAGE', 'Quebra de Reutilizável / Utensílio'), ('EXPIRATION', 'Baixa por Validade Vencida'), ('RETURN_TO_SUPPLIER', 'Devolução ao Fornecedor'), ('CUSTOMER_RETURN', 'Retorno de Cliente'), ('INVENTORY_ADJUSTMENT_POSITIVE', 'Ajuste de Inventário (+)'), ('INVENTORY_ADJUSTMENT_NEGATIVE', 'Ajuste de Inventário (-)'), ('INITIAL_BALANCE', 'Implantação de Saldo'), ('ASSET_DISPOSAL', 'Baixa Patrimonial'), ('in', 'Entrada (Legado)'), ('out', 'Saída (Legado)'), ('adjustment', 'Ajuste (Legado)'), ('sale', 'Venda (Legado)'), ('inventory', 'Inventário (Legado)')], db_index=True, max_length=40),
        ),
    ]
