# Generated by Django 5.1.15 on 2026-10-01 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_local_fiscal_allowed'),
        ('restaurants', '0010_unico_so_entre_ativos'),
        ('stock', '0007_alter_stockmovement_movement_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stocklabeltemplate',
            name='unique_label_template_by_branch',
        ),
        migrations.RemoveConstraint(
            model_name='stocklocation',
            name='unique_stock_location_by_branch',
        ),
        migrations.AddConstraint(
            model_name='stocklabeltemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('branch', 'name'), name='unique_label_template_by_branch'),
        ),
        migrations.AddConstraint(
            model_name='stocklocation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('branch', 'name'), name='unique_stock_location_by_branch'),
        ),
    ]
