# Generated by Django 5.1.15 on 2026-09-05 23:19

import apps.storefront.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_cosmosconfig'),
        ('menu', '0005_ingredient_account_scoped'),
        ('restaurants', '0004_branch_district_restaurant_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=60)),
                ('preview_image', models.URLField(blank=True, default='')),
                ('project_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('theme', models.JSONField(blank=True, default=dict)),
                ('seo', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('catalog', models.ForeignKey(blank=True, help_text='Cardápio (menu.Menu) que define quais produtos aparecem no site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storefront_sites', to='menu.menu')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='menu_site', to='restaurants.restaurant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='MenuPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=140)),
                ('is_home', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('draft_data', models.JSONField(blank=True, default=dict)),
                ('published_data', models.JSONField(blank=True, default=dict)),
                ('seo', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicada'), ('archived', 'Arquivada')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storefront_pages_published', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_pages', to='restaurants.restaurant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='storefront.menusite')),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MenuDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('domain_type', models.CharField(choices=[('subdomain', 'Subdomínio'), ('custom', 'Domínio próprio')], default='subdomain', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, default='', max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ssl_status', models.CharField(choices=[('pending', 'Pendente'), ('issuing', 'Emitindo'), ('active', 'Ativo'), ('error', 'Erro')], default='pending', max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_domains', to='restaurants.restaurant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='storefront.menusite')),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='MenuAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(max_length=400, upload_to=apps.storefront.models.asset_upload_path)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_assets', to='restaurants.restaurant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'restaurant'], name='storefront__account_9d2599_idx'), models.Index(fields=['restaurant', 'checksum'], name='storefront__restaur_33b37c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MenuPageVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.PositiveIntegerField(default=1)),
                ('label', models.CharField(blank=True, default='', max_length=150)),
                ('origin', models.CharField(choices=[('publish', 'Publicação'), ('restore', 'Restauração'), ('manual', 'Manual')], default='publish', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='storefront.menupage')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_page_versions', to='restaurants.restaurant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-number'],
                'indexes': [models.Index(fields=['page', 'number'], name='storefront__page_id_e45074_idx')],
                'constraints': [models.UniqueConstraint(fields=('page', 'number'), name='unique_page_version_number')],
            },
        ),
        migrations.AddIndex(
            model_name='menusite',
            index=models.Index(fields=['account', 'is_active'], name='storefront__account_e7bf19_idx'),
        ),
        migrations.AddIndex(
            model_name='menusite',
            index=models.Index(fields=['slug'], name='storefront__slug_79a9b3_idx'),
        ),
        migrations.AddIndex(
            model_name='menupage',
            index=models.Index(fields=['site', 'status'], name='storefront__site_id_b27527_idx'),
        ),
        migrations.AddIndex(
            model_name='menupage',
            index=models.Index(fields=['account', 'restaurant'], name='storefront__account_68c7a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='menupage',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='unique_menu_page_slug_per_site'),
        ),
        migrations.AddConstraint(
            model_name='menupage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_home', True)), fields=('site',), name='unique_menu_page_home_per_site'),
        ),
        migrations.AddIndex(
            model_name='menudomain',
            index=models.Index(fields=['hostname', 'verified'], name='storefront__hostnam_d23e3d_idx'),
        ),
        migrations.AddConstraint(
            model_name='menudomain',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('site',), name='unique_primary_domain_per_site'),
        ),
    ]
