# Generated by Django 5.1.15 on 2026-09-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_menusite_theme_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusite',
            name='header',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
