# Generated by Django 5.1.15 on 2026-07-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurant_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='require_open_cash_register',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='stock_deduction_timing',
            field=models.CharField(choices=[('payment', 'No pagamento'), ('kitchen', 'No envio à cozinha')], default='payment', max_length=20),
        ),
    ]
