# Generated by Django 5.1.15 on 2026-07-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_require_open_cash_register_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cash_action_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
