# Generated by Django 5.1.15 on 2026-09-07 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('restaurants', '0004_branch_district_restaurant_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='logo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_logos', to='images.image'),
        ),
    ]
