# Generated by Django 5.1.15 on 2026-09-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cancellation_grace_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='max_commands_per_table',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
