# Generated by Django 5.1.15 on 2026-09-23 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurant_commands_per_table_and_grace'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='command',
            name='restaurants_restaur_5b6901_idx',
        ),
        migrations.RemoveField(
            model_name='command',
            name='status',
        ),
    ]
