# Generated by Django 5.1.15 on 2026-09-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_comanda_status_calculado'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='item_cancel_window_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
