# Generated by Django 5.1.15 on 2026-09-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_regras_de_cancelamento_de_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='metafields',
            field=models.JSONField(blank=True, default=dict, help_text='Campos adicionais livres. Dicionário raso, valores escalares curtos.'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='require_operator_code',
            field=models.BooleanField(default=False, help_text='Pedir o código do operador antes de criar pedido ou lançar item (app do garçom).'),
        ),
    ]
