# Generated by Django 5.1.15 on 2026-10-01 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_local_fiscal_allowed'),
        ('restaurants', '0009_campos_adicionais_e_codigo_do_operador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='branch',
            name='unique_branch_name_by_restaurant',
        ),
        migrations.RemoveConstraint(
            model_name='command',
            name='unique_command_number_by_restaurant',
        ),
        migrations.RemoveConstraint(
            model_name='command',
            name='unique_command_code_by_restaurant',
        ),
        migrations.RemoveConstraint(
            model_name='deliveryman',
            name='unique_deliveryman_by_branch',
        ),
        migrations.RemoveConstraint(
            model_name='deliveryzone',
            name='unique_delivery_zone_by_branch',
        ),
        migrations.RemoveConstraint(
            model_name='table',
            name='unique_table_number_by_branch',
        ),
        migrations.RemoveConstraint(
            model_name='table',
            name='unique_table_code_by_branch',
        ),
        migrations.RemoveConstraint(
            model_name='tablesector',
            name='unique_table_sector_by_branch',
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('restaurant', 'name'), name='unique_branch_name_by_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='command',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('restaurant', 'number'), name='unique_command_number_by_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='command',
            constraint=models.UniqueConstraint(condition=models.Q(('code__gt', ''), ('deleted_at__isnull', True)), fields=('restaurant', 'code'), name='unique_command_code_by_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='deliveryman',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('branch', 'name'), name='unique_deliveryman_by_branch'),
        ),
        migrations.AddConstraint(
            model_name='deliveryzone',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('branch', 'name'), name='unique_delivery_zone_by_branch'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('branch', 'number'), name='unique_table_number_by_branch'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(condition=models.Q(('code__gt', ''), ('deleted_at__isnull', True)), fields=('branch', 'code'), name='unique_table_code_by_branch'),
        ),
        migrations.AddConstraint(
            model_name='tablesector',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('branch', 'name'), name='unique_table_sector_by_branch'),
        ),
    ]
