# Generated by Django 5.1.15 on 2026-10-02 04:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_restaurant_quick_scale_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='cash_closing_tolerance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cash_closing_tolerance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
