# Generated by Django 5.1.15 on 2026-07-28 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_passwordresetrequest'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to='accounts.account')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='core_idempo_created_c8a89f_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'key'), name='idempotency_unique_key_per_account')],
            },
        ),
    ]
