# Generated by Django 5.1.15 on 2026-09-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_kds_rules_and_item_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='kdscolumn',
            name='blocks_cancel',
            field=models.BooleanField(default=False, help_text='Item nesta coluna não pode ser cancelado (exige autorização).'),
        ),
    ]
