# Generated by Django 5.1.15 on 2026-08-28 07:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_role_is_account_admin'),
        ('menu', '0001_initial'),
        ('restaurants', '0002_command_current_table_commandmovementlog'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DFeSyncState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ult_nsu', models.CharField(default='000000000000000', max_length=15)),
                ('max_nsu', models.CharField(default='000000000000000', max_length=15)),
                ('last_cstat', models.CharField(blank=True, max_length=3)),
                ('last_reason', models.TextField(blank=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('next_allowed_at', models.DateTimeField(blank=True, null=True)),
                ('is_syncing', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.restaurant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado de Sincronização DF-e',
                'verbose_name_plural': 'Estados de Sincronização DF-e',
            },
        ),
        migrations.CreateModel(
            name='InboundNFe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('access_key', models.CharField(db_index=True, max_length=44)),
                ('nsu', models.CharField(blank=True, max_length=15)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('series', models.CharField(blank=True, max_length=10)),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('supplier_cnpj', models.CharField(blank=True, max_length=14)),
                ('supplier_name', models.CharField(blank=True, max_length=180)),
                ('total_products', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_invoice', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(max_length=30)),
                ('manifestation_status', models.CharField(blank=True, max_length=30)),
                ('summary_xml', models.TextField(blank=True)),
                ('full_xml', models.TextField(blank=True)),
                ('stock_applied_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.restaurant')),
                ('stock_applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NF-e de Entrada',
                'verbose_name_plural': 'NF-es de Entrada',
            },
        ),
        migrations.CreateModel(
            name='InboundNFeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('item_number', models.PositiveIntegerField()),
                ('supplier_code', models.CharField(blank=True, max_length=60)),
                ('ean', models.CharField(blank=True, max_length=14)),
                ('description', models.CharField(max_length=255)),
                ('ncm', models.CharField(blank=True, max_length=8)),
                ('cfop', models.CharField(blank=True, max_length=4)),
                ('commercial_unit', models.CharField(blank=True, max_length=10)),
                ('commercial_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('commercial_unit_value', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('taxable_unit', models.CharField(blank=True, max_length=10)),
                ('taxable_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('taxable_unit_value', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('product_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('conversion_factor', models.DecimalField(decimal_places=6, default=1, max_digits=12)),
                ('received_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.ingredient')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inbound_nfe.inboundnfe')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.product')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.restaurant')),
                ('stock_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_nfe_item', to='stock.stockmovement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item da NF-e',
                'verbose_name_plural': 'Itens da NF-e',
            },
        ),
        migrations.CreateModel(
            name='SupplierItemMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('supplier_cnpj', models.CharField(db_index=True, max_length=14)),
                ('supplier_code', models.CharField(blank=True, max_length=60)),
                ('supplier_ean', models.CharField(blank=True, max_length=14)),
                ('conversion_factor', models.DecimalField(decimal_places=6, default=1, max_digits=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.ingredient')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.product')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.restaurant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mapeamento de Fornecedor',
                'verbose_name_plural': 'Mapeamentos de Fornecedores',
            },
        ),
        migrations.AddConstraint(
            model_name='inboundnfe',
            constraint=models.UniqueConstraint(fields=('account', 'access_key'), name='unique_inbound_nfe_by_account'),
        ),
        migrations.AddConstraint(
            model_name='inboundnfeitem',
            constraint=models.UniqueConstraint(fields=('invoice', 'item_number'), name='unique_item_by_invoice'),
        ),
        migrations.AddConstraint(
            model_name='supplieritemmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier_code', ''), _negated=True), fields=('account', 'supplier_cnpj', 'supplier_code'), name='unique_mapping_by_supplier_code'),
        ),
        migrations.AddConstraint(
            model_name='supplieritemmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier_ean', ''), _negated=True), fields=('account', 'supplier_cnpj', 'supplier_ean'), name='unique_mapping_by_supplier_ean'),
        ),
    ]
