# Generated by Django 5.1.15 on 2026-09-02 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_nfe', '0002_dfe_distribution_document'),
        ('menu', '0002_product_gtin_product_unique_product_gtin_by_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieritemmapping',
            name='confidence',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Nível de confiança da correspondência (0-100%).', max_digits=5),
        ),
        migrations.AddField(
            model_name='supplieritemmapping',
            name='confirmed_by_user',
            field=models.BooleanField(default=True, help_text='Se o vínculo foi validado/confirmado manualmente pelo usuário.'),
        ),
        migrations.AddField(
            model_name='supplieritemmapping',
            name='last_used_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supplieritemmapping',
            name='supplier_description',
            field=models.CharField(blank=True, help_text='Descrição original do produto na NF-e do fornecedor.', max_length=255),
        ),
        migrations.AlterField(
            model_name='supplieritemmapping',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=6, default=1, help_text='Fator de conversão: 1 unidade fiscal = factor * unidade estoque.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='supplieritemmapping',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_mappings', to='menu.ingredient'),
        ),
        migrations.AlterField(
            model_name='supplieritemmapping',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_mappings', to='menu.product'),
        ),
    ]
