# Generated by Django 5.1.15 on 2026-09-02 17:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_is_account_admin'),
        ('inbound_nfe', '0003_supplieritemmapping_confidence_and_more'),
        ('restaurants', '0002_command_current_table_commandmovementlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inboundnfe',
            options={'ordering': ['-issue_date', '-created_at'], 'verbose_name': 'NF-e de Entrada', 'verbose_name_plural': 'NF-es de Entrada'},
        ),
        migrations.AddField(
            model_name='inboundnfe',
            name='distribution_type',
            field=models.CharField(default='summary', max_length=20),
        ),
        migrations.AddField(
            model_name='inboundnfe',
            name='receiving_status',
            field=models.CharField(default='not_started', max_length=30),
        ),
        migrations.AddField(
            model_name='inboundnfe',
            name='xml_status',
            field=models.CharField(default='summary_only', max_length=30),
        ),
        migrations.AlterField(
            model_name='inboundnfe',
            name='manifestation_status',
            field=models.CharField(blank=True, default='none', max_length=30),
        ),
        migrations.CreateModel(
            name='NFeManifestation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('access_key', models.CharField(db_index=True, max_length=44)),
                ('event_type', models.CharField(choices=[('science', 'Ciência da Operação'), ('confirm', 'Confirmação da Operação'), ('unknown', 'Desconhecimento da Operação'), ('not_performed', 'Operação não Realizada')], max_length=30)),
                ('event_code', models.CharField(help_text='Código do evento SEFAZ: 210210, 210200, 210220, 210240.', max_length=6)),
                ('sequence', models.PositiveIntegerField(default=1, help_text='Número sequencial do evento (nSeqEvento).')),
                ('event_datetime', models.DateTimeField(help_text='Data e hora do evento timezone-aware.')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('SIGNED', 'Assinado'), ('SENT', 'Enviado'), ('ACCEPTED', 'Aceito'), ('REJECTED', 'Rejeitado'), ('ERROR', 'Erro')], default='PENDING', max_length=20)),
                ('sefaz_batch_status', models.CharField(blank=True, help_text='cStat do lote (retEnvEvento).', max_length=10)),
                ('sefaz_batch_reason', models.TextField(blank=True, help_text='xMotivo do lote.')),
                ('sefaz_event_status', models.CharField(blank=True, help_text='cStat do evento individual (infEvento/cStat).', max_length=10)),
                ('sefaz_event_reason', models.TextField(blank=True, help_text='xMotivo do evento individual.')),
                ('protocol', models.CharField(blank=True, help_text='Número de protocolo do registro do evento (nProt).', max_length=50)),
                ('request_xml', models.TextField(blank=True, help_text='XML enviado à SEFAZ assinado com XMLDSig.')),
                ('response_xml', models.TextField(blank=True, help_text='XML bruto recebido na resposta da SEFAZ.')),
                ('registered_at', models.DateTimeField(blank=True, help_text='Data/hora de registro do evento retornado pela SEFAZ (dhRegEvento).', null=True)),
                ('reason', models.TextField(blank=True, help_text='Justificativa (obrigatória para Operação não Realizada - 210240).')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestations', to='inbound_nfe.inboundnfe')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.restaurant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manifestação do Destinatário',
                'verbose_name_plural': 'Manifestações do Destinatário',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('account', 'invoice', 'event_code', 'sequence'), name='unique_manifestation_event_seq')],
            },
        ),
    ]
