# Generated by Django 5.1.15 on 2026-09-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_nfe', '0004_alter_inboundnfe_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfemanifestation',
            name='history',
            field=models.JSONField(blank=True, default=list, help_text='Histórico de tentativas anteriores de envio do evento para auditoria.'),
        ),
    ]
