# Generated by Django 5.1.15 on 2026-09-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_nfe', '0005_nfemanifestation_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='DFeGlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_cooldown_blocking', models.BooleanField(default=True, help_text='Se desmarcado, o sistema NÃO bloqueia novas requisições preventivamente. Útil para testes ou para contornar bloqueios.', verbose_name='Ativar Bloqueio Preventivo de Cooldown')),
                ('cooldown_interval_minutes', models.PositiveIntegerField(default=30, help_text='Tempo de espera recomendado entre consultas sem novos documentos (padrão: 30 a 60 min).', verbose_name='Intervalo Mínimo entre Consultas (minutos)')),
                ('cooldown_no_docs_minutes', models.PositiveIntegerField(default=60, help_text='Tempo de espera quando a SEFAZ informa que não há mais documentos na fila.', verbose_name='Cooldown para Nenhum Documento / cStat 137 (minutos)')),
                ('cooldown_error_minutes', models.PositiveIntegerField(default=5, help_text='Tempo de espera após falha de comunicação ou erro genérico.', verbose_name='Cooldown para Erros Temporários (minutos)')),
                ('blocked_message_template', models.TextField(default='A última consulta foi realizada há menos de {interval} minutos. Para proteger seu CNPJ contra penalidades da SEFAZ, aguarde até {time} (faltam {minutes} min).', help_text='Texto exibido aos clientes na tela. Variáveis disponíveis: {time} (horário permitido), {minutes} (minutos restantes) e {interval} (intervalo configurado).', verbose_name='Mensagem de Bloqueio Preventivo')),
                ('blocked_cstat_656_message_template', models.TextField(default='Consulta bloqueada temporariamente por Consumo Indevido na SEFAZ. Próxima requisição permitida após às {time} (faltam {minutes} min).', help_text='Texto exibido aos clientes na tela quando a SEFAZ bloqueia por cStat 656. Variáveis disponíveis: {time} e {minutes}.', verbose_name='Mensagem de Consumo Indevido (cStat 656)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Configuração Global SEFAZ',
                'verbose_name_plural': 'Configurações Globais SEFAZ',
            },
        ),
    ]
