# Generated by Django 5.1.15 on 2026-09-04 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_is_account_admin'),
        ('inbound_nfe', '0006_dfeglobalconfig'),
        ('menu', '0004_remove_product_unique_product_code_by_branch_and_more'),
        ('restaurants', '0002_command_current_table_commandmovementlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supplieritemmapping',
            name='unique_mapping_by_supplier_code',
        ),
        migrations.RemoveConstraint(
            model_name='supplieritemmapping',
            name='unique_mapping_by_supplier_ean',
        ),
        migrations.AddConstraint(
            model_name='supplieritemmapping',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('supplier_code', ''), _negated=True), ('deleted_at__isnull', True)), fields=('account', 'supplier_cnpj', 'supplier_code'), name='unique_mapping_by_supplier_code'),
        ),
        migrations.AddConstraint(
            model_name='supplieritemmapping',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('supplier_ean', ''), _negated=True), ('deleted_at__isnull', True)), fields=('account', 'supplier_cnpj', 'supplier_ean'), name='unique_mapping_by_supplier_ean'),
        ),
    ]
