# Generated by Django 5.1.15 on 2026-09-04 21:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_is_account_admin'),
        ('inbound_nfe', '0007_remove_supplieritemmapping_unique_mapping_by_supplier_code_and_more'),
        ('restaurants', '0002_command_current_table_commandmovementlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundnfe',
            name='cancellation_event_nsu',
            field=models.CharField(blank=True, help_text='NSU do evento de cancelamento distribuído pela SEFAZ.', max_length=15),
        ),
        migrations.AddField(
            model_name='inboundnfe',
            name='cancellation_protocol',
            field=models.CharField(blank=True, help_text='Protocolo de homologação do evento de cancelamento.', max_length=60),
        ),
        migrations.AddField(
            model_name='inboundnfe',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Justificativa ou motivo do cancelamento registrado na SEFAZ.'),
        ),
        migrations.AddField(
            model_name='inboundnfe',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o cancelamento foi homologado pela SEFAZ.', null=True),
        ),
        migrations.AddField(
            model_name='inboundnfe',
            name='fiscal_status',
            field=models.CharField(choices=[('UNKNOWN', 'Desconhecido'), ('AUTHORIZED', 'Autorizada'), ('CANCELLED', 'Cancelada'), ('DENIED', 'Denegada')], db_index=True, default='AUTHORIZED', help_text='Situação fiscal da NF-e perante a SEFAZ.', max_length=20),
        ),
        migrations.AddField(
            model_name='inboundnfe',
            name='last_status_check_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora da última consulta de situação pontual realizada na SEFAZ.', null=True),
        ),
        migrations.AddField(
            model_name='inboundnfe',
            name='last_status_cstat',
            field=models.CharField(blank=True, help_text='Último cStat retornado pela consulta de situação da SEFAZ.', max_length=10),
        ),
        migrations.AddField(
            model_name='inboundnfe',
            name='last_status_reason',
            field=models.TextField(blank=True, help_text='Último xMotivo retornado pela consulta de situação da SEFAZ.'),
        ),
        migrations.CreateModel(
            name='NFeIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('issue_type', models.CharField(choices=[('CANCELLED_AFTER_RECEIPT', 'NF-e Cancelada Após Recebimento'), ('CANCELLED_AFTER_STOCK_MOVEMENT', 'NF-e Cancelada com Estoque Já Movimentado/Consumido'), ('CANCELLED_WITH_ASSETS', 'NF-e Cancelada com Bens Patrimoniais Criados'), ('STATUS_INCONSISTENCY', 'Inconsistência de Situação Fiscal')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('OPEN', 'Em Aberto'), ('RESOLVED', 'Resolvido'), ('IGNORED', 'Ignorado / Justificado')], db_index=True, default='OPEN', max_length=20)),
                ('description', models.TextField(help_text='Detalhamento da pendência e instruções de resolução para o gerente.')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Justificativa ou nota explicativa de resolução da ocorrência.')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('nfe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='inbound_nfe.inboundnfe')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.restaurant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pendência Operacional de NF-e',
                'verbose_name_plural': 'Pendências Operacionais de NF-e',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NFeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('access_key', models.CharField(db_index=True, help_text='Chave de acesso da NF-e à qual o evento pertence.', max_length=44)),
                ('nsu', models.CharField(blank=True, help_text='NSU do evento recebido no DFe.', max_length=15)),
                ('schema', models.CharField(blank=True, help_text='Schema do evento (ex: procEventoNFe_v1.00.xsd, resEvento_v1.01.xsd).', max_length=100)),
                ('event_code', models.CharField(db_index=True, help_text='Código do tipo de evento (tpEvento) - Ex: 110111.', max_length=10)),
                ('event_description', models.CharField(blank=True, help_text='Descrição do evento (descEvento ou xEvento).', max_length=120)),
                ('sequence', models.PositiveIntegerField(default=1, help_text='Número sequencial do evento para a chave (nSeqEvento).')),
                ('event_datetime', models.DateTimeField(blank=True, help_text='Data e hora do evento (dhEvento).', null=True)),
                ('protocol', models.CharField(blank=True, help_text='Número do protocolo de homologação do evento (nProt).', max_length=60)),
                ('sefaz_cstat', models.CharField(blank=True, help_text='Código de status retornado pela SEFAZ para o evento (cStat).', max_length=10)),
                ('sefaz_reason', models.TextField(blank=True, help_text='Motivo retornado pela SEFAZ (xMotivo).')),
                ('xml', models.TextField(help_text='XML bruto do evento recebido.')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Data/hora em que as consequências operacionais foram aplicadas.', null=True)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSED', 'Processado'), ('IGNORED', 'Ignorado'), ('ERROR', 'Erro')], db_index=True, default='PENDING', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('nfe', models.ForeignKey(blank=True, help_text='NF-e associada a este evento (pode ser nula se o evento chegar antes da nota).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='inbound_nfe.inboundnfe')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.restaurant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de NF-e',
                'verbose_name_plural': 'Eventos de NF-e',
                'ordering': ['-event_datetime', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('account', 'access_key', 'event_code', 'sequence'), name='unique_nfe_event_by_account_key_code_seq')],
            },
        ),
    ]
