# Generated by Django 5.1.15 on 2026-09-11 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_nfe', '0008_inboundnfe_cancellation_event_nsu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundnfe',
            name='ignored_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que a nota fiscal foi marcada como ignorada.', null=True),
        ),
        migrations.AddField(
            model_name='inboundnfe',
            name='ignored_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que marcou a nota como ignorada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inboundnfe',
            name='ignored_reason',
            field=models.TextField(blank=True, help_text='Motivo pelo qual a nota fiscal foi ignorada.'),
        ),
        migrations.AddField(
            model_name='inboundnfeitem',
            name='ignored_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o item foi marcado como ignorado.', null=True),
        ),
        migrations.AddField(
            model_name='inboundnfeitem',
            name='ignored_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que marcou o item como ignorado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inboundnfeitem',
            name='ignored_reason',
            field=models.CharField(blank=True, help_text='Motivo de ter ignorado o item da nota.', max_length=255),
        ),
        migrations.AddField(
            model_name='inboundnfeitem',
            name='is_ignored',
            field=models.BooleanField(db_index=True, default=False, help_text='Se marcado, o item é ignorado e não dá entrada no estoque nem exige vínculo.'),
        ),
    ]
