# Generated by Django 5.1.15 on 2026-07-24 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_kdscolumn'),
        ('orders', '0002_order_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='kds_column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='kitchen.kdscolumn'),
        ),
    ]
