# Generated by Django 5.1.15 on 2026-09-20 22:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_local_fiscal_allowed'),
        ('kitchen', '0002_kds_rules_and_item_positions'),
        ('menu', '0010_alter_product_controls_stock_and_more'),
        ('orders', '0008_backfill_cancellation_details'),
        ('restaurants', '0006_restaurant_commands_per_table_and_grace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='restaurants.command'),
        ),
        migrations.CreateModel(
            name='CommandBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('serial', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('batch_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('sent_at', models.DateTimeField()),
                ('dispatch_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.branch')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='restaurants.command')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.restaurant')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_batches_sent', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['batch_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommandItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('variations', models.JSONField(blank=True, default=list)),
                ('customer_note', models.TextField(blank=True)),
                ('production_sector', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued during grace period'), ('sent', 'Sent'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('comped', 'Comped')], db_index=True, default='pending', max_length=24)),
                ('launched_at', models.DateTimeField(auto_now_add=True)),
                ('sent_to_kitchen_at', models.DateTimeField(blank=True, null=True)),
                ('preparation_started_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('command_status', models.CharField(choices=[('pending', 'Pendente na comanda'), ('billed', 'Cobrado'), ('cancelled', 'Cancelado na comanda')], db_index=True, default='pending', max_length=16)),
                ('command_closed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='orders.commandbatch')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.branch')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='command_items', to='restaurants.command')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('kds_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_items', to='kitchen.kdscolumn')),
                ('launched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_items_launched', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='command_items', to='menu.product')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.restaurant')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_items', to='restaurants.table')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_items_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['launched_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='command_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='orders.commanditem'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('command_item',), name='unique_order_item_per_command_item'),
        ),
        migrations.AddConstraint(
            model_name='commandbatch',
            constraint=models.UniqueConstraint(fields=('command', 'batch_number'), name='unique_batch_number_per_command'),
        ),
        migrations.AddIndex(
            model_name='commanditem',
            index=models.Index(fields=['branch', 'production_sector', 'status'], name='orders_comm_branch__6d222c_idx'),
        ),
        migrations.AddIndex(
            model_name='commanditem',
            index=models.Index(fields=['command', 'command_status'], name='orders_comm_command_2bd4c9_idx'),
        ),
    ]
