# Generated by Django 5.1.15 on 2026-09-21 23:58

from django.db import migrations, models


def encerrar_pagamentos_de_pedidos_cancelados(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Payment = apps.get_model('payments', 'Payment')
    CashMovement = apps.get_model('payments', 'CashMovement')
    for pedido in Order.objects.using(schema_editor.connection.alias).filter(status='cancelled').iterator():
        if pedido.payment_status in ('paid', 'refunded'):
            Order.objects.using(schema_editor.connection.alias).filter(pk=pedido.pk).update(
                payment_status='refunded'
            )
            continue
        recebimentos = Payment.objects.using(schema_editor.connection.alias).filter(
            order_id=pedido.pk, status__in=['pending', 'approved']
        )
        CashMovement.objects.using(schema_editor.connection.alias).filter(
            payment_id__in=recebimentos.values('pk'), status='approved'
        ).update(status='cancelled')
        recebimentos.update(status='cancelled')
        Order.objects.using(schema_editor.connection.alias).filter(pk=pedido.pk).update(
            payment_status='cancelled'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitem_command_commandbatch_commanditem_and_more'),
        ('payments', '0002_pdv_terminal_and_session_exclusivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.RunPython(encerrar_pagamentos_de_pedidos_cancelados, migrations.RunPython.noop),
    ]
