# Generated by Django 5.1.15 on 2026-09-25 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """O cupom entra no pedido em campo proprio, ao lado do `discount`.

    Separado de proposito: `discount` e a decisao de um gerente naquele pedido e
    `coupon_discount` e uma regra que o cliente exerceu, reavaliada a cada
    recalculo. Somados numa coluna so, o recalculo apagaria o abatimento dado a
    mao toda vez que reavaliasse o cupom.
    """


    dependencies = [
        ('orders', '0011_commanditemaddon'),
        ('promotions', '0001_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='promotions.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
