# Generated by Django 5.1.15 on 2026-09-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_cupom_no_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='commanditem',
            name='metafields',
            field=models.JSONField(blank=True, default=dict, help_text='Campos adicionais livres. Dicionário raso, valores escalares curtos.'),
        ),
        migrations.AddField(
            model_name='order',
            name='metafields',
            field=models.JSONField(blank=True, default=dict, help_text='Campos adicionais livres. Dicionário raso, valores escalares curtos.'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='metafields',
            field=models.JSONField(blank=True, default=dict, help_text='Campos adicionais livres. Dicionário raso, valores escalares curtos.'),
        ),
    ]
