# Generated by Django 5.1.15 on 2026-08-28 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_is_account_admin'),
        ('invoices', '0002_initial'),
        ('menu', '0001_initial'),
        ('restaurants', '0002_command_current_table_commandmovementlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gtin',
            field=models.CharField(blank=True, db_index=True, help_text='GTIN/EAN/UPC do produto, somente dígitos.', max_length=14),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('gtin', ''), _negated=True), fields=('branch', 'gtin'), name='unique_product_gtin_by_branch'),
        ),
    ]
