# Generated by Django 5.1.15 on 2026-08-29 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_seed_system_roles'),
        ('invoices', '0004_fiscal_profile_shared_by_account'),
        ('menu', '0001_initial'),
        ('restaurants', '0003_hash_plain_cash_action_passwords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ean',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Código de barras (EAN/GTIN). Opcional, único na conta.', max_length=32),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['account', 'ean'], name='menu_produc_account_805712_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('ean', ''), _negated=True), ('deleted_at__isnull', True)), fields=('account', 'ean'), name='unique_product_ean_by_account'),
        ),
    ]
