# Generated by Django 5.1.15 on 2026-08-30 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_consumption_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_consumption_unit',
            field=models.CharField(blank=True, choices=[('unit', 'Unit'), ('kg', 'Kg'), ('g', 'g'), ('l', 'L'), ('ml', 'ml')], max_length=12),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_ingredient',
            field=models.ForeignKey(blank=True, help_text='Insumo consumido por unidade vendida, para produtos sem ficha tecnica.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_products', to='menu.ingredient'),
        ),
        migrations.AddField(
            model_name='productaddon',
            name='consumption_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productaddon',
            name='consumption_unit',
            field=models.CharField(blank=True, choices=[('unit', 'Unit'), ('kg', 'Kg'), ('g', 'g'), ('l', 'L'), ('ml', 'ml')], max_length=12),
        ),
        migrations.AddField(
            model_name='productaddon',
            name='ingredient',
            field=models.ForeignKey(blank=True, help_text='Insumo consumido por unidade vendida deste adicional.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addons', to='menu.ingredient'),
        ),
    ]
