# Generated by Django 5.1.15 on 2026-09-02 01:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_is_account_admin'),
        ('menu', '0002_product_gtin_product_unique_product_gtin_by_branch'),
        ('restaurants', '0002_command_current_table_commandmovementlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_negative_stock',
            field=models.BooleanField(default=False, help_text='Permite estoque negativo (padrão False).'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text='Marca do produto/fabricante.', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='current_average_cost',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Custo médio ponderado atual.', max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='default_useful_life_months',
            field=models.PositiveIntegerField(blank=True, help_text='Vida útil estimada em meses.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('INGREDIENT', 'Insumo / Ingrediente'), ('RESALE_PRODUCT', 'Mercadoria p/ Revenda'), ('CONSUMABLE', 'Material de Consumo'), ('REUSABLE_MATERIAL', 'Material Reutilizável (Utensílio)'), ('EQUIPMENT', 'Equipamento Operacional'), ('FIXED_ASSET', 'Ativo Fixo / Patrimônio'), ('PACKAGING', 'Embalagem'), ('SERVICE', 'Serviço'), ('OTHER', 'Outro')], db_index=True, default='RESALE_PRODUCT', help_text='Classificação de finalidade do item.', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='last_purchase_cost',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Último custo unitário de compra.', max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='maximum_stock',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Estoque máximo desejado.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_stock',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Estoque mínimo de segurança.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, help_text='Modelo ou especificação.', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_cleaning_schedule',
            field=models.BooleanField(default=False, help_text='Exige rotina periódica de limpeza/higienização.'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_expiration_control',
            field=models.BooleanField(default=False, help_text='Exige data de validade na entrada.'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_lot_control',
            field=models.BooleanField(default=False, help_text='Exige número de lote na entrada.'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_maintenance',
            field=models.BooleanField(default=False, help_text='Exige plano de manutenção periódica.'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_serial_number',
            field=models.BooleanField(default=False, help_text='Exige número de série individual.'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_unit',
            field=models.CharField(default='UN', help_text='Unidade padrão no estoque (ex: UN, KG, L, G, ML).', max_length=12),
        ),
        migrations.AddField(
            model_name='product',
            name='tracking_mode',
            field=models.CharField(choices=[('QUANTITY', 'Por Quantidade'), ('LOT', 'Por Lote e Validade'), ('SERIALIZED', 'Serializado (Patrimônio)')], db_index=True, default='QUANTITY', help_text='Tipo de rastreamento físico (quantidade, lote ou serializado).', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='controls_stock',
            field=models.BooleanField(default=True, help_text='Se o produto movimenta estoque físico.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Por unidade, ou por kg quando pricing_unit=kg.', max_digits=12),
        ),
        migrations.CreateModel(
            name='ProductUnitConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source_unit', models.CharField(help_text='Unidade de compra / fiscal (ex: CX, FD, BD, LT)', max_length=12)),
                ('target_unit', models.CharField(help_text='Unidade interna de estoque (ex: UN, KG, L, G, ML)', max_length=12)),
                ('factor', models.DecimalField(decimal_places=6, default=1, help_text='Multiplicador de conversão: 1 source_unit = factor * target_unit', max_digits=12)),
                ('supplier_cnpj', models.CharField(blank=True, help_text='CNPJ do fornecedor se for regra específica.', max_length=14)),
                ('supplier_product_code', models.CharField(blank=True, help_text='Código do produto no fornecedor.', max_length=60)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversions', to='menu.product')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.restaurant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversão de Unidade de Produto',
                'verbose_name_plural': 'Conversões de Unidades de Produtos',
                'constraints': [models.UniqueConstraint(fields=('account', 'product', 'source_unit', 'supplier_cnpj', 'supplier_product_code'), name='unique_unit_conversion_rule')],
            },
        ),
    ]
