# Generated by Django 5.1.15 on 2026-09-04 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_is_account_admin'),
        ('invoices', '0003_fiscalconfig_certificate_cnpj_and_more'),
        ('menu', '0003_product_allow_negative_stock_product_brand_and_more'),
        ('restaurants', '0002_command_current_table_commandmovementlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_code_by_branch',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_gtin_by_branch',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('branch', 'internal_code'), name='unique_product_code_by_branch'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('gtin', ''), _negated=True), ('deleted_at__isnull', True)), fields=('branch', 'gtin'), name='unique_product_gtin_by_branch'),
        ),
    ]
