# Generated by Django 5.1.15 on 2026-08-31 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_product_stock_consumption_quantity_and_more'),
        ('stock', '0004_supplier_stockentryitem_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Fornecedor padrao sugerido nas entradas deste insumo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='stock.supplier'),
        ),
    ]
