# Generated by Django 5.1.15 on 2026-09-06 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_seed_storefront_role_and_permissions'),
        ('menu', '0005_ingredient_account_scoped'),
        ('restaurants', '0004_branch_district_restaurant_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['display_order', 'created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='menuitem',
            name='unique_product_per_menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='item_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(choices=[('catalog', 'Catalogo (curadoria de produtos)'), ('navigation', 'Navegacao (cabecalho, rodape)'), ('banner', 'Banners (carrossel)'), ('showcase', 'Vitrine (categorias ou produtos em destaque)')], db_index=True, default='catalog', max_length=20),
        ),
        migrations.AddField(
            model_name='menu',
            name='source',
            field=models.CharField(choices=[('manual', 'Itens escolhidos a mao'), ('all_categories', 'Todas as categorias ativas'), ('category_products', 'Produtos de uma categoria'), ('best_sellers', 'Mais vendidos'), ('promotions', 'Em promocao')], default='manual', max_length=24),
        ),
        migrations.AddField(
            model_name='menu',
            name='source_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_of_menus', to='menu.productcategory'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.productcategory'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='menu/items/'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='item_type',
            field=models.CharField(choices=[('product', 'Produto'), ('category', 'Categoria'), ('image', 'Imagem / banner'), ('custom', 'Link personalizado')], db_index=True, default='product', max_length=20),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='opens_in_new_tab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Item pai, para submenus da barra de navegacao.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(max_length=140),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.product'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['account', 'menu_type', 'is_active'], name='menu_menu_account_be856d_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['menu', 'parent', 'display_order'], name='menu_menuit_menu_id_14597b_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['menu', 'item_type'], name='menu_menuit_menu_id_8f17fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('account', 'slug'), name='unique_menu_slug_by_account'),
        ),
    ]
