# Generated by Django 5.1.15 on 2026-07-30 21:08

from django.db import migrations, models


def copy_primary_restaurant(apps, schema_editor):
    Product = apps.get_model("menu", "Product")
    through = Product.restaurants.through
    through.objects.bulk_create(
        [
            through(product_id=product_id, restaurant_id=restaurant_id)
            for product_id, restaurant_id in Product.objects.values_list("id", "restaurant_id")
        ],
        ignore_conflicts=True,
    )


def reverse_copy(apps, schema_editor):
    Product = apps.get_model("menu", "Product")
    Product.restaurants.through.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_product_sector'),
        ('restaurants', '0005_command_reusable_and_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='restaurants',
            field=models.ManyToManyField(blank=True, help_text='Restaurantes da conta que podem comercializar este produto.', related_name='available_products', to='restaurants.restaurant'),
        ),
        migrations.RunPython(copy_primary_restaurant, reverse_copy),
    ]
