# Generated by Django 5.1.15 on 2026-09-07 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('menu', '0006_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='logo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_logos', to='images.image'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='logo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_logos', to='images.image'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='logo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variation_logos', to='images.image'),
        ),
    ]
