# Generated by Django 5.1.15 on 2026-09-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_product_unique_product_code_by_branch_and_more'),
        ('menu', '0008_recipe_preparation_instructions'),
    ]

    operations = [
    ]
