# Generated by Django 5.1.15 on 2026-09-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_merge_20260919_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='controls_stock',
            field=models.BooleanField(default=False),
        ),
    ]
