# Generated by Django 5.1.15 on 2026-10-01 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_local_fiscal_allowed'),
        ('images', '0002_import_legacy_images'),
        ('menu', '0011_preco_base_do_produto'),
        ('restaurants', '0009_campos_adicionais_e_codigo_do_operador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='menu',
            name='unique_menu_name_by_branch',
        ),
        migrations.RemoveConstraint(
            model_name='productaddon',
            name='unique_addon_by_branch',
        ),
        migrations.RemoveConstraint(
            model_name='productcategory',
            name='unique_category_by_branch_parent',
        ),
        migrations.RemoveConstraint(
            model_name='productunitconversion',
            name='unique_unit_conversion_rule',
        ),
        migrations.RemoveConstraint(
            model_name='productvariation',
            name='unique_variation_by_product',
        ),
        migrations.RemoveConstraint(
            model_name='recipeitem',
            name='unique_ingredient_by_recipe',
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('branch', 'name'), name='unique_menu_name_by_branch'),
        ),
        migrations.AddConstraint(
            model_name='productaddon',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('branch', 'name'), name='unique_addon_by_branch'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('branch', 'name', 'parent'), name='unique_category_by_branch_parent'),
        ),
        migrations.AddConstraint(
            model_name='productunitconversion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('account', 'product', 'source_unit', 'supplier_cnpj', 'supplier_product_code'), name='unique_unit_conversion_rule'),
        ),
        migrations.AddConstraint(
            model_name='productvariation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('product', 'name'), name='unique_variation_by_product'),
        ),
        migrations.AddConstraint(
            model_name='recipeitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('recipe', 'ingredient'), name='unique_ingredient_by_recipe'),
        ),
    ]
