/**
 * Conteudo publico da Central de Ajuda.
 *
 * A organizacao espelha a sidebar do sistema. Cada artigo explica para que a
 * tela serve, um fluxo recomendado e de onde normalmente vem cada informacao.
 * Nao inclua tokens, senhas, CNPJ de clientes ou qualquer dado real aqui: a
 * rota /docs pode ser acessada sem autenticacao.
 */
export const helpSections = [
  {
    id: "principal",
    title: "Principal",
    description: "Acompanhe a operacao do dia, os pedidos e o preparo da cozinha.",
    articles: [
      {
        id: "home",
        title: "Home",
        icon: "home",
        summary: "Visao rapida do restaurante e atalhos para as tarefas mais usadas.",
        purpose: "Use a Home para conferir o movimento atual e entrar rapidamente nas areas operacionais. Os indicadores respeitam o restaurante selecionado no topo da sidebar.",
        steps: [
          "Confira qual restaurante esta selecionado antes de analisar os numeros.",
          "Revise pedidos abertos, movimento do dia e alertas operacionais.",
          "Use os atalhos da pagina para abrir pedidos, produtos, caixa ou relatorios.",
        ],
        data: [
          "Os totais sao calculados automaticamente a partir de pedidos, pagamentos e itens do KDS.",
          "O seletor de restaurante aparece para proprietarios e administradores com acesso global.",
        ],
        tips: ["Se um numero parecer incorreto, confira primeiro o restaurante e o periodo selecionados."],
      },
      {
        id: "pedidos",
        title: "Pedidos",
        icon: "receipt-text",
        summary: "Consulte vendas abertas, aguardando pagamento, pagas, canceladas ou estornadas.",
        purpose: "A tela concentra o historico operacional dos pedidos. A criacao acontece no PDV; aqui voce pesquisa, abre detalhes, edita itens permitidos e acompanha pagamento, producao e entrega.",
        steps: [
          "Use Novo pedido para iniciar uma venda no PDV.",
          "Filtre por periodo, status, cliente, mesa, comanda ou numero do pedido.",
          "Abra o detalhe para conferir itens, totais, pagamentos e historico.",
          "Use Editar itens somente enquanto o pedido ainda permite alteracoes.",
        ],
        data: [
          "Mesa e comanda vêm dos respectivos cadastros.",
          "Cliente e endereco vêm do cadastro de Clientes ou sao informados durante a venda.",
          "Status de pagamento muda quando recebimentos, estornos ou cancelamentos sao registrados.",
        ],
        tips: ["Pedidos pagos ou cancelados ficam protegidos contra alteracoes comuns."],
      },
      {
        id: "kds",
        title: "KDS Cozinha",
        icon: "soup",
        summary: "Organize o preparo em quadros e colunas visuais para a cozinha.",
        purpose: "O KDS recebe os itens enviados pelo PDV e permite acompanhar a passagem por etapas como entrada, preparo, pronto e concluido.",
        steps: [
          "Escolha a estacao correta para o setor da cozinha.",
          "Acompanhe os cards novos na coluna de entrada.",
          "Mova os cards conforme o preparo avancar.",
          "Conclua somente depois que o item estiver pronto ou entregue, conforme o fluxo configurado.",
        ],
        data: [
          "Os itens chegam dos pedidos enviados para a cozinha.",
          "Setor do produto, estacao KDS, colunas e SLA determinam onde o card aparece e quando alerta.",
        ],
        tips: ["Se um item nao aparecer, confira o setor do produto e o vinculo da estacao KDS."],
      },
    ],
  },
  {
    id: "operacao",
    title: "Operação",
    description: "Cadastros e rotinas que sustentam o atendimento diario.",
    articles: [
      {
        id: "kds-estacoes",
        title: "Estações KDS",
        icon: "soup",
        summary: "Crie os quadros usados por cozinha, bar, expedicao ou outros setores.",
        purpose: "Uma estacao representa um quadro do KDS de um restaurante. Ela agrupa colunas e pode receber regras de tempo de atendimento.",
        steps: [
          "Crie uma estacao com um nome reconhecivel, como Cozinha ou Bar.",
          "Selecione o restaurante ao qual ela pertence.",
          "Informe o SLA inicial e mantenha a estacao ativa.",
          "Depois, confira no KDS se os itens do setor correto estao chegando ao quadro.",
        ],
        data: ["Nome e fluxo vêm da organizacao fisica da producao do restaurante."],
        tips: ["Prefira uma estacao por fluxo real de producao, evitando quadros duplicados com a mesma funcao."],
      },
      {
        id: "sla",
        title: "SLAs",
        icon: "timer",
        summary: "Defina tempos-alvo e alertas para preparo e atendimento.",
        purpose: "SLAs tornam atrasos visiveis no KDS. Uma regra pode valer para restaurantes, estacoes inteiras ou colunas especificas.",
        steps: [
          "Defina um nome, tipo e prioridade para a regra.",
          "Informe o tempo-alvo e quando o alerta deve aparecer.",
          "Vincule os restaurantes e as estacoes ou colunas desejadas.",
          "Acompanhe o resultado no KDS antes de reduzir os tempos.",
        ],
        data: ["Os tempos devem vir da meta operacional definida pelo responsavel da cozinha ou atendimento."],
        tips: ["Uma regra de coluna e mais especifica e deve prevalecer sobre a regra geral da estacao."],
      },
      {
        id: "mesas",
        title: "Mesas",
        icon: "armchair",
        summary: "Cadastre mesas, capacidade, setor e codigos para leitura.",
        purpose: "As mesas identificam o local de consumo e podem ser abertas no PDV por numero, lista, codigo de barras ou QR Code.",
        steps: [
          "Cadastre primeiro os Setores, como Salao, Varanda ou Piso superior.",
          "Crie individualmente ou use Criar em lote para uma sequencia de mesas.",
          "Informe numero, setor e capacidade.",
          "Use Ver codigos ou Imprimir etiquetas para gerar identificadores fisicos.",
        ],
        data: ["Numeracao, capacidade e divisao por setor vêm do mapa real do estabelecimento."],
        tips: ["Desative uma mesa temporariamente em vez de reutilizar seu numero durante um atendimento."],
      },
      {
        id: "comandas",
        title: "Comandas",
        icon: "receipt-text",
        summary: "Gerencie cartoes ou codigos reutilizaveis para consumo.",
        purpose: "Cada comanda pode ser vinculada a um pedido em andamento e liberada novamente depois do pagamento. Ela pode ou nao estar associada a uma mesa.",
        steps: [
          "Crie comandas individualmente ou em lote.",
          "Use numeracao e codigo unicos dentro do restaurante.",
          "Imprima etiquetas ou cartoes com codigo de barras/QR.",
          "No PDV, leia a comanda para abrir ou retomar o pedido correspondente.",
        ],
        data: ["A quantidade e a numeracao vêm do conjunto de cartoes fisicos usado pelo restaurante."],
        tips: ["Uma comanda ocupada deve ser encerrada pelo fluxo do pedido; nao a desative para tentar libera-la."],
      },
      {
        id: "caixa",
        title: "Caixa",
        icon: "wallet",
        summary: "Abra e feche turnos, registre sangrias e suprimentos e confira divergencias.",
        purpose: "O caixa representa o dinheiro e os recebimentos de um turno em uma estacao. Cada abertura registra operador, valor inicial, movimentos e valor contado no fechamento.",
        steps: [
          "Vincule os operadores autorizados ao caixa cadastrado.",
          "Na abertura, conte fisicamente o dinheiro e informe o valor encontrado.",
          "Registre todo suprimento ou sangria durante o turno, sempre com motivo.",
          "No fechamento, conte novamente sem depender do valor esperado.",
          "Se houver diferenca, solicite a aprovacao exigida pelo restaurante.",
        ],
        data: [
          "Valor de abertura e fechamento vêm da contagem fisica.",
          "Vendas em dinheiro entram automaticamente; cartao e PIX permanecem no historico de pagamentos.",
          "A senha de acoes do caixa e definida no cadastro do restaurante.",
        ],
        tips: ["Nunca use sangria para corrigir uma venda; estorne ou ajuste a operacao que originou a diferenca."],
      },
      {
        id: "formas-pagamento",
        title: "Formas de pagamento",
        icon: "credit-card",
        summary: "Configure dinheiro, PIX, cartoes, vouchers e outras formas aceitas.",
        purpose: "As formas cadastradas aparecem no recebimento do PDV e determinam como o pagamento sera classificado nos relatorios.",
        steps: [
          "Cadastre um nome que o operador reconheca.",
          "Escolha o tipo correto: dinheiro, cartao, PIX, voucher ou outro.",
          "Ative Exige referencia quando for necessario informar NSU, autorizacao, comprovante ou identificador externo.",
          "Desative formas antigas sem apagar o historico.",
        ],
        data: ["A lista vem dos meios realmente contratados com bancos, adquirentes e operadoras de beneficio."],
        tips: ["Nao crie varias formas com nomes diferentes para o mesmo meio sem necessidade contabil."],
      },
      {
        id: "clientes",
        title: "Clientes",
        icon: "users",
        summary: "Centralize identificacao, contato e endereco de entrega.",
        purpose: "O cadastro agiliza pedidos recorrentes, entregas e identificacao do consumidor em documentos fiscais quando necessario.",
        steps: [
          "Informe pelo menos o nome do cliente.",
          "Adicione telefone e e-mail para contato.",
          "Cadastre CPF apenas quando fornecido e necessario.",
          "Preencha endereco, complemento e referencia para entregas.",
          "Mantenha observacoes internas objetivas e adequadas.",
        ],
        data: ["Todos os dados devem ser informados pelo proprio cliente e usados apenas para a operacao autorizada."],
        tips: ["Confirme o endereco a cada entrega; um cadastro antigo pode estar correto, mas nao ser o destino daquele pedido."],
      },
    ],
  },
  {
    id: "cardapio",
    title: "Cardápio",
    description: "Produtos, classificacoes, complementos e fichas tecnicas.",
    articles: [
      {
        id: "produtos",
        title: "Produtos",
        icon: "book-open",
        summary: "Cadastre o que sera vendido, preparado, pesado e tributado.",
        purpose: "O produto conecta preco, disponibilidade, setor de producao, codigo de scanner, perfil fiscal e, quando habilitado, estoque e receita.",
        steps: [
          "Informe nome, restaurantes que usam o produto e codigo interno.",
          "Cadastre o EAN/GTIN exatamente como aparece na embalagem, preservando zeros.",
          "Defina preco, unidade de cobranca, categoria e tipo.",
          "Escolha o setor que deve preparar o item e o tempo medio.",
          "Configure variacoes, adicionais, disponibilidade e perfil fiscal quando aplicavel.",
        ],
        data: [
          "EAN/GTIN vem da embalagem ou do fornecedor; produtos proprios podem usar um codigo interno criado pela operacao.",
          "NCM e regras fiscais devem ser confirmados com o contador.",
          "Preco, tempo e setor vêm da administracao e da cozinha.",
        ],
        tips: ["EAN e codigo interno devem ser unicos para o scanner localizar somente um produto."],
      },
      {
        id: "categorias",
        title: "Categorias",
        icon: "tag",
        summary: "Agrupe produtos para facilitar busca, exibicao e relatorios.",
        purpose: "Categorias organizam o cardapio, como Lanches, Bebidas, Sobremesas ou Combos. Elas podem ser reutilizadas entre restaurantes da conta.",
        steps: [
          "Crie nomes curtos e reconheciveis.",
          "Defina a ordem de exibicao.",
          "Associe cada produto a categoria adequada.",
          "Desative categorias que nao devem aparecer sem apagar os produtos.",
        ],
        data: ["A estrutura vem da organizacao comercial do cardapio."],
        tips: ["Evite categorias com apenas um produto quando uma classificacao existente ja atende."],
      },
      {
        id: "adicionais",
        title: "Adicionais",
        icon: "plus",
        summary: "Cadastre complementos cobrados ou opcionais dos produtos.",
        purpose: "Adicionais permitem incluir itens como bacon, queijo, molhos ou acompanhamentos e direciona-los ao setor correto.",
        steps: [
          "Informe nome, preco e setor de producao.",
          "Mantenha o adicional ativo.",
          "Abra o produto e vincule os adicionais permitidos.",
          "Teste a selecao no PDV e a impressao na cozinha.",
        ],
        data: ["Nome, custo operacional, preco e setor vêm da ficha comercial do produto."],
        tips: ["Um adicional so aparece no produto depois que o vinculo entre eles for salvo."],
      },
      {
        id: "ingredientes",
        title: "Ingredientes",
        icon: "flask",
        summary: "Liste insumos usados nas receitas e no controle de estoque.",
        purpose: "Ingredientes formam a base das fichas tecnicas. Com Logistica habilitada, ajudam a calcular consumo e estoque minimo.",
        steps: [
          "Cadastre o nome e a unidade de medida usada na cozinha.",
          "Informe estoque minimo quando houver controle logistico.",
          "Associe o ingrediente às receitas com a quantidade de consumo.",
          "Padronize a unidade para evitar conversoes inconsistentes.",
        ],
        data: ["Descricoes, unidades e consumo vêm da ficha tecnica e das embalagens de compra."],
        tips: ["Nao misture kg e unidade para o mesmo ingrediente sem definir uma conversao operacional confiavel."],
      },
      {
        id: "receitas",
        title: "Receitas",
        icon: "salad",
        summary: "Monte fichas tecnicas e relacione consumo de ingredientes aos produtos.",
        purpose: "A receita registra rendimento e ingredientes de um produto. Ela pode calcular custo e dar baixa automatica no estoque conforme as vendas.",
        steps: [
          "Escolha o produto final.",
          "Informe o rendimento real da preparacao.",
          "Adicione cada ingrediente e a quantidade consumida.",
          "Revise o custo calculado.",
          "Ative baixa automatica somente depois de conferir unidades e rendimento.",
        ],
        data: ["Use a ficha tecnica validada pela cozinha, com pesos e rendimentos medidos."],
        tips: ["Uma receita incorreta afeta custo e estoque; valide primeiro em poucos produtos."],
      },
    ],
  },
  {
    id: "ecommerce",
    title: "E-commerce",
    description: "Publicacao de cardapios digitais para canais externos.",
    articles: [
      {
        id: "cardapios-digitais",
        title: "Cardápios digitais",
        icon: "book-marked",
        summary: "Organize quais produtos aparecem em cada canal e horario.",
        purpose: "Um cardapio digital seleciona canal, identificador publico e janela de disponibilidade para exibir produtos fora da retaguarda.",
        steps: [
          "Defina nome e slug simples para o cardapio.",
          "Escolha o canal de publicacao.",
          "Configure horario inicial e final quando houver restricao.",
          "Associe os produtos e confira preco e disponibilidade antes de divulgar.",
        ],
        data: ["Nome, canal e horarios vêm da estrategia comercial do restaurante."],
        tips: ["Use um slug sem espacos e evite troca-lo depois que o endereco ja tiver sido divulgado."],
      },
    ],
  },
  {
    id: "entrega",
    title: "Entrega",
    description: "Area de atendimento e equipe responsavel pelas entregas.",
    articles: [
      {
        id: "zonas-entrega",
        title: "Zonas de entrega",
        icon: "map-pin",
        summary: "Defina bairros, faixas de CEP, taxas e regras da area atendida.",
        purpose: "As zonas ajudam a validar se um endereco e atendido e qual taxa de entrega deve ser aplicada.",
        steps: [
          "Separe a cidade em areas operacionais coerentes.",
          "Cadastre nome, abrangencia e taxa de cada zona.",
          "Defina limites de pedido ou prazo quando o cadastro oferecer essas regras.",
          "Teste enderecos proximos das bordas antes de liberar.",
        ],
        data: ["CEPs, bairros, distancia, custo e prazo vêm do mapa de cobertura definido pela operacao."],
        tips: ["Revise periodicamente taxas e tempos conforme transito e custo dos entregadores."],
      },
      {
        id: "entregadores",
        title: "Entregadores",
        icon: "truck",
        summary: "Cadastre profissionais e veiculos usados na distribuicao.",
        purpose: "O cadastro identifica quem recebeu cada entrega e permite acompanhar disponibilidade e tipo de veiculo.",
        steps: [
          "Informe nome e dados de contato.",
          "Registre o tipo de veiculo e a identificacao necessaria.",
          "Mantenha apenas entregadores disponiveis como ativos.",
          "Associe o entregador ao pedido no despacho.",
        ],
        data: ["Dados pessoais e do veiculo devem ser fornecidos pelo profissional e tratados conforme a politica da empresa."],
        tips: ["Desative o cadastro ao encerrar a prestacao; nao reutilize um entregador antigo para outra pessoa."],
      },
    ],
  },
  {
    id: "logistica",
    title: "Logística",
    description: "Posicao dos insumos, entradas, saidas e locais fisicos.",
    articles: [
      {
        id: "estoque",
        title: "Estoque",
        icon: "package",
        summary: "Acompanhe saldos, movimentos, compras, consumo e ajustes.",
        purpose: "O estoque combina entradas manuais e de compra com baixas de venda ou receita. A tela mostra a posicao conhecida pelo sistema.",
        steps: [
          "Cadastre ingredientes, produtos controlados e locais de estoque.",
          "Registre entradas com documento ou motivo.",
          "Use transferencias para mover saldo entre locais.",
          "Faca contagens periodicas e registre ajustes com justificativa.",
          "Investigue saldos negativos em vez de apenas zera-los.",
        ],
        data: ["Quantidades vêm de notas de compra, contagens fisicas, receitas e vendas registradas."],
        tips: ["Estoque do sistema e uma estimativa operacional; a contagem fisica continua sendo a referencia de auditoria."],
      },
      {
        id: "locais-estoque",
        title: "Locais de estoque",
        icon: "clipboard-list",
        summary: "Represente depositos, cozinhas, freezers e outros pontos de armazenagem.",
        purpose: "Locais separam o saldo conforme a posicao fisica e tornam transferencias e inventarios mais claros.",
        steps: [
          "Mapeie os lugares reais onde os insumos ficam armazenados.",
          "Crie nomes objetivos, como Deposito seco ou Freezer cozinha.",
          "Associe entradas e contagens ao local correto.",
          "Registre transferencias sempre que o material mudar de local.",
        ],
        data: ["A lista vem da estrutura fisica de armazenamento de cada restaurante."],
        tips: ["Nao crie um local generico se a equipe precisa saber onde encontrar o item."],
      },
    ],
  },
  {
    id: "financeiro",
    title: "Financeiro",
    description: "Recebimentos, documentos fiscais e integracao Focus NFe.",
    articles: [
      {
        id: "historico-pagamentos",
        title: "Histórico de pagamentos",
        icon: "dollar-sign",
        summary: "Consulte recebimentos aprovados, cancelados e estornados.",
        purpose: "A tela permite rastrear qual pedido originou um pagamento, forma utilizada, valor, referencia e horario.",
        steps: [
          "Filtre pelo restaurante e periodo corretos.",
          "Pesquise pelo pedido, forma ou referencia do comprovante.",
          "Abra o registro para conferir valor, troco e status.",
          "Compare divergencias com o comprovante da adquirente ou banco.",
        ],
        data: ["Os registros sao criados pelo recebimento no PDV; NSU e referencias vêm da maquininha, banco ou comprovante."],
        tips: ["Nao altere a forma para conciliar um erro; cancele ou estorne e registre novamente conforme a permissao."],
      },
      {
        id: "notas-fiscais",
        title: "Notas fiscais",
        icon: "shield-check",
        summary: "Acompanhe emissao, autorizacao, rejeicao, cancelamento, XML e DANFE.",
        purpose: "Cada documento fiscal fica relacionado ao pedido e ao restaurante emitente. O status informa se a nota foi autorizada pela SEFAZ ou precisa de correcao.",
        steps: [
          "Filtre por restaurante, periodo ou status.",
          "Abra rejeicoes e leia a mensagem completa antes de reenviar.",
          "Corrija o cadastro que causou o problema, como produto, cliente ou configuracao fiscal.",
          "Baixe XML e DANFE somente de documentos autorizados.",
          "Cancele dentro do prazo e sempre informe justificativa valida.",
        ],
        data: ["Chave, protocolo, XML e retorno vêm da SEFAZ por meio do provedor fiscal configurado."],
        tips: ["Homologacao gera documentos de teste; producao gera documentos fiscais reais."],
      },
      {
        id: "perfis-fiscais",
        title: "Perfis fiscais",
        icon: "percentage",
        summary: "Reutilize NCM, CFOP, origem, CST/CSOSN e aliquotas entre produtos.",
        purpose: "O perfil evita repetir a mesma tributacao em cada produto e padroniza a montagem dos itens da NF-e/NFC-e.",
        steps: [
          "Separe grupos de produtos que realmente compartilham a mesma tributacao.",
          "Informe NCM, origem e CFOP.",
          "Preencha CSOSN ou CST conforme o CRT do emitente.",
          "Configure ICMS, PIS, COFINS, CEST e tributos aproximados quando aplicaveis.",
          "Associe o perfil aos produtos e valide primeiro em homologacao.",
        ],
        data: ["Solicite NCM, CFOP, CST/CSOSN e aliquotas ao contador; CEST pode vir da classificacao fiscal do produto."],
        tips: ["O StarChef armazena a configuracao, mas nao substitui a classificacao feita pelo profissional contabil."],
      },
      {
        id: "configuracao-cosmos",
        title: "Configuração Cosmos",
        icon: "search",
        summary: "Use o catálogo Cosmos para sugerir NCM e CEST pelo nome do perfil fiscal.",
        purpose: "A configuração pertence à conta StarChef. Quando estiver ativa, o formulário de perfil fiscal pesquisa produtos semelhantes e preenche os campos disponibilizados pela Cosmos.",
        steps: [
          "Crie uma conta no portal Bluesoft Cosmos e abra a área da API.",
          "Copie o X-Cosmos-Token e o User-Agent exibidos para sua conta.",
          "Informe os dois valores no StarChef, ative a integração e salve.",
          "Abra Perfis fiscais e digite um nome com pelo menos três caracteres.",
          "Revise a sugestão de NCM e CEST antes de salvar o perfil.",
        ],
        data: [
          "Token e User-Agent são fornecidos pela Cosmos e ficam isolados nesta conta StarChef.",
          "Nome do produto, GPC, NCM e CEST vêm do catálogo Cosmos quando disponíveis.",
          "CFOP, CST/CSOSN e alíquotas continuam dependendo da operação e da orientação contábil.",
        ],
        tips: ["O plano gratuito possui limite diário. Resultados já consultados ficam em cache para economizar chamadas."],
        warning: "Os dados da Cosmos são sugestões cadastrais e não substituem a validação do contador.",
      },
      {
        id: "configuracao-focus",
        title: "Configuração Focus",
        icon: "settings",
        summary: "Conecte a conta integradora e sincronize os restaurantes emitentes.",
        purpose: "Esta configuracao pertence à conta StarChef e guarda o token mestre, URLs, webhook e comportamento de sincronizacao com a Focus NFe.",
        steps: [
          "Obtenha o token do ambiente correto no painel da Focus NFe.",
          "Informe URLs de producao e homologacao e ajuste o timeout somente se necessario.",
          "Configure a URL publica do webhook e um segredo de autorizacao.",
          "Use Dry run apenas para testar o cadastro sem criar ou alterar a empresa na Focus.",
          "Depois configure cada emitente em Restaurantes > Configuracao fiscal.",
        ],
        data: [
          "Token mestre e credenciais da integracao vêm da conta integradora Focus NFe.",
          "Certificado A1, CRT, IE, CSC e idToken pertencem ao CNPJ de cada restaurante emitente.",
          "CSC e idToken são fornecidos pela SEFAZ da UF para o ambiente escolhido.",
        ],
        tips: ["Nunca publique token, senha do certificado ou CSC em chamados, capturas de tela ou documentos publicos."],
        warning: "Homologacao e producao sao ambientes separados. Confirme o ambiente antes de sincronizar ou emitir.",
      },
    ],
  },
  {
    id: "gestao",
    title: "Gestão",
    description: "Relatorios, unidades, acessos e equipamentos do restaurante.",
    articles: [
      {
        id: "relatorios",
        title: "Relatórios",
        icon: "bar-chart-3",
        summary: "Analise resultados por periodo, restaurante e dimensao operacional.",
        purpose: "Os relatorios consolidam dados registrados pelo PDV, pagamentos, produtos e usuarios. Sempre confirme periodo, restaurante e status incluídos antes de comparar valores.",
        steps: [
          "Selecione o restaurante ou a visao consolidada.",
          "Defina o periodo desejado.",
          "Aplique os filtros especificos do relatorio.",
          "Compare totais com os detalhes antes de exportar ou tomar uma decisao.",
        ],
        data: ["Todos os indicadores vêm dos registros operacionais do proprio StarChef."],
        tips: ["Um pedido aberto ou pagamento pendente pode aparecer de forma diferente de uma venda concluida."],
      },
      {
        id: "relatorio-geral",
        title: "Relatórios: Visão geral",
        icon: "layout-dashboard",
        summary: "Indicadores consolidados de vendas, pedidos, ticket e operacao.",
        purpose: "Use para uma leitura executiva do periodo e para localizar rapidamente variacoes que merecem investigacao em relatorios detalhados.",
        steps: ["Escolha periodo e escopo.", "Compare faturamento, quantidade de pedidos e ticket medio.", "Abra o relatorio especifico do indicador que mudou."],
        data: ["Os totais vêm de pedidos e pagamentos considerados no periodo."],
        tips: ["Nao compare periodos de duracoes diferentes sem considerar dias e horarios de funcionamento."],
      },
      {
        id: "relatorio-vendas",
        title: "Relatórios: Vendas",
        icon: "trending-up",
        summary: "Acompanhe valor vendido, descontos, taxas e evolucao no periodo.",
        purpose: "Ajuda a entender quando e onde as vendas aconteceram e como descontos e taxas afetaram o total.",
        steps: ["Defina o periodo.", "Selecione o restaurante.", "Compare vendas brutas, descontos, taxas e vendas liquidas."],
        data: ["Valores vêm dos totais finais dos pedidos e de seus ajustes."],
        tips: ["Confira cancelamentos e estornos ao conciliar o valor com recebimentos."],
      },
      {
        id: "relatorio-pedidos",
        title: "Relatórios: Pedidos",
        icon: "receipt-text",
        summary: "Analise volume, tipo, status e motivos de cancelamento.",
        purpose: "Mostra o comportamento operacional dos pedidos por canal e situacao.",
        steps: ["Escolha periodo e restaurante.", "Compare balcao, mesa, comanda, entrega e retirada.", "Revise pedidos cancelados e justificativas."],
        data: ["Tipo e status são gravados durante o fluxo de cada pedido."],
        tips: ["Volume alto com ticket menor pode ser normal para um canal; compare dimensoes em conjunto."],
      },
      {
        id: "relatorio-produtos",
        title: "Relatórios: Produtos",
        icon: "book-open",
        summary: "Veja quantidade vendida, receita e preco medio por produto.",
        purpose: "Use para identificar campeoes de venda, itens com pouca saida e diferencas por categoria ou setor.",
        steps: ["Selecione periodo e restaurante.", "Filtre categoria ou setor quando necessário.", "Ordene por quantidade, total ou preco medio."],
        data: ["Os dados vêm dos itens efetivamente registrados nos pedidos."],
        tips: ["Considere produtos promocionais e adicionais antes de comparar preco medio com preco atual."],
      },
      {
        id: "relatorio-pagamentos",
        title: "Relatórios: Pagamentos",
        icon: "credit-card",
        summary: "Concilie valores por forma de pagamento e status.",
        purpose: "Agrupa recebimentos em dinheiro, PIX, cartoes, vouchers e outros meios para apoiar a conferencia financeira.",
        steps: ["Escolha o mesmo periodo do fechamento externo.", "Compare por forma de pagamento.", "Abra o Historico de pagamentos para investigar divergencias."],
        data: ["Valores e referencias vêm dos recebimentos registrados no PDV."],
        tips: ["A data da venda e a data de liquidacao da adquirente podem ser diferentes."],
      },
      {
        id: "relatorio-garcons",
        title: "Relatórios: Garçons",
        icon: "users",
        summary: "Acompanhe pedidos e valores por responsavel pelo atendimento.",
        purpose: "Mostra a distribuicao da operacao entre usuarios identificados como responsaveis pelos pedidos.",
        steps: ["Selecione periodo e restaurante.", "Compare quantidade e total por garcom.", "Confirme se os pedidos foram atribuídos ao usuario correto."],
        data: ["O responsavel vem do usuario selecionado ou autenticado durante a abertura do pedido."],
        tips: ["Use o indicador para gestao, nao como unica medida de desempenho ou qualidade."],
      },
      {
        id: "relatorio-restaurantes",
        title: "Relatórios: Restaurantes",
        icon: "store",
        summary: "Compare unidades da mesma conta com indicadores consolidados.",
        purpose: "Permite comparar quantidade de pedidos, faturamento e ticket medio entre restaurantes.",
        steps: ["Use o escopo Todos os restaurantes.", "Defina um periodo comum às unidades.", "Compare total, pedidos e ticket medio considerando dias de funcionamento."],
        data: ["A unidade vem do restaurante associado a cada pedido e pagamento."],
        tips: ["Valide se todas as unidades operaram durante todo o periodo antes de criar metas comparativas."],
      },
      {
        id: "restaurantes",
        title: "Restaurantes",
        icon: "store",
        summary: "Cadastre unidades, dados de contato, endereco e regras operacionais.",
        purpose: "O restaurante e o principal escopo operacional. Produtos, pedidos, caixas, equipamentos e configuracao fiscal são associados a ele.",
        steps: [
          "Informe nome fantasia, razao social e CNPJ da unidade.",
          "Cadastre contato e endereco completos.",
          "Defina taxa de servico e se pagamentos exigem caixa aberto.",
          "Configure uma senha simples e segura para acoes sensiveis do caixa.",
          "No menu da linha, abra Configuracao fiscal para preparar NF-e/NFC-e.",
        ],
        data: ["Razao social, CNPJ e endereco vêm do cartao CNPJ e documentos oficiais da empresa."],
        tips: ["Dados fiscais são por emitente: use as informacoes do cliente que opera aquele restaurante, nao as da StarChef."],
      },
      {
        id: "setores",
        title: "Setores",
        icon: "armchair",
        summary: "Organize salao e producao em areas reconhecidas pela equipe.",
        purpose: "Setores podem agrupar mesas, produtos, impressoras, balancas e fluxos de cozinha.",
        steps: ["Mapeie as areas reais do restaurante.", "Crie nomes curtos como Salao, Cozinha ou Bar.", "Associe os cadastros correspondentes.", "Desative o setor quando deixar de ser usado."],
        data: ["A lista vem da divisao fisica e operacional da unidade."],
        tips: ["Evite nomes quase iguais; isso dificulta escolher impressora e producao corretas."],
      },
      {
        id: "usuarios",
        title: "Usuários",
        icon: "user-cog",
        summary: "Crie acessos individuais e vincule perfil, restaurante e cargo.",
        purpose: "Cada pessoa deve usar seu proprio usuario para que pedidos, caixa, aprovacoes e auditoria identifiquem corretamente o responsavel.",
        steps: [
          "Cadastre nome de usuario e e-mail validos.",
          "Defina uma senha inicial e solicite a troca segura.",
          "Escolha o perfil funcional correto.",
          "Restrinja ao restaurante quando a pessoa nao precisar de acesso global.",
          "Desative imediatamente acessos de quem saiu da operacao.",
        ],
        data: ["Nome, contato, funcao e unidade vêm do cadastro interno da equipe."],
        tips: ["Nunca compartilhe um usuario entre varias pessoas; isso remove a rastreabilidade das operacoes."],
      },
      {
        id: "perfis-acesso",
        title: "Perfis de acesso",
        icon: "shield-check",
        summary: "Consulte permissoes dos perfis fixos usados pela equipe.",
        purpose: "Perfis como Garcom, Caixa, Gerente e Administrador determinam o conjunto basico de permissoes e limites, como desconto maximo.",
        steps: ["Abra um perfil para revisar permissoes.", "Escolha o perfil apropriado no cadastro do usuario.", "Teste o acesso com um usuario de homologacao antes de liberar à equipe."],
        data: ["As responsabilidades vêm da politica interna da empresa; os perfis disponiveis são mantidos pelo sistema."],
        tips: ["Aplique o menor nivel de acesso suficiente para a funcao exercida."],
      },
      {
        id: "terminais-pdv",
        title: "Terminais do PDV",
        icon: "monitor",
        summary: "Identifique e revogue instalacoes desktop ou navegadores que operam o caixa.",
        purpose: "Um terminal nasce automaticamente na primeira operacao. A tela permite trocar o nome tecnico por algo reconhecivel e impedir uma instalacao antiga de abrir caixa.",
        steps: [
          "Localize a instalacao pelo tipo, restaurante e ultimo contato.",
          "Renomeie para algo fisico, como Balcao 01.",
          "Confira o papel na rede local.",
          "Desative e informe o motivo quando o equipamento for perdido, substituido ou reinstalado.",
        ],
        data: ["O identificador e criado automaticamente pelo aplicativo; nome e restaurante são definidos pelo administrador."],
        tips: ["Nao copie o identificador de uma instalacao para outra maquina."],
      },
      {
        id: "impressoras",
        title: "Impressoras",
        icon: "zap",
        summary: "Configure impressao por sistema, USB/serial ou rede TCP/IP.",
        purpose: "A configuracao informa ao Caixa Principal qual equipamento deve receber comandas, recibos, etiquetas ou documentos de um setor.",
        steps: [
          "Instale e teste a impressora no sistema operacional quando usar o driver do Windows/Linux.",
          "Cadastre nome, driver e tipo de conexao.",
          "Informe exatamente o nome do sistema, porta serial ou IP e porta TCP.",
          "Vincule o setor quando a impressora for exclusiva.",
          "Execute uma impressao de teste no PDV antes de ativar impressao automatica.",
        ],
        data: ["Nome do dispositivo vem do sistema operacional; IP, porta, linguagem e parametros vêm do manual ou da configuracao da impressora."],
        tips: ["Para impressoras de rede, reserve o IP no roteador para evitar mudanca após reinicializacao."],
      },
      {
        id: "balancas",
        title: "Balanças",
        icon: "scale",
        summary: "Integre leitura de peso, produto por quilo e impressao de pesagem.",
        purpose: "O agente local do PDV le a porta serial conforme o protocolo da balanca e transforma pesos estaveis em itens do pedido.",
        steps: [
          "Instale o driver do adaptador serial quando necessario.",
          "Identifique a porta COM ou /dev/ttyUSB usada pelo equipamento.",
          "Selecione o protocolo descrito no manual da balanca.",
          "Vincule produto por quilo e impressora quando o fluxo exigir.",
          "Teste estabilidade e unidade antes de ativar lancamento automatico.",
        ],
        data: ["Porta, velocidade e protocolo vêm do sistema operacional e do manual tecnico do fabricante."],
        tips: ["No Linux, o usuario que executa o PDV precisa ter permissao para acessar a porta serial."],
      },
    ],
  },
];

export const helpArticles = helpSections.flatMap((section) =>
  section.articles.map((article) => ({ ...article, sectionId: section.id, sectionTitle: section.title })),
);
