# Generated by Django 5.1.15 on 2026-09-25 01:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_account_local_fiscal_allowed'),
        ('customers', '0002_grupos_de_clientes'),
        ('menu', '0011_preco_base_do_produto'),
        ('orders', '0011_commanditemaddon'),
        ('restaurants', '0008_regras_de_cancelamento_de_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_index=True, help_text='O que o cliente informa. Guardado em MAIÚSCULAS.', max_length=40)),
                ('name', models.CharField(blank=True, max_length=140)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('discount_kind', models.CharField(choices=[('percent', 'Percentual sobre o subtotal'), ('amount', 'Valor em reais'), ('free_delivery', 'Entrega grátis')], default='percent', max_length=16)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Teto em reais para o desconto percentual. Vazio = sem teto.', max_digits=12, null=True)),
                ('minimum_order_value', models.DecimalField(decimal_places=2, default=0, help_text='Mínimo em produtos, SEM taxa de serviço e SEM entrega.', max_digits=12)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(default=0, help_text='Total de usos do cupom. 0 = ilimitado.')),
                ('usage_limit_per_customer', models.PositiveIntegerField(default=0, help_text='Usos por cliente. 0 = ilimitado.')),
                ('single_use_per_customer', models.BooleanField(default=False, help_text='Compra única por cliente (equivale a 1 uso por cliente).')),
                ('first_purchase_only', models.BooleanField(default=False, help_text='Só vale para quem ainda não tem pedido pago.')),
                ('requires_document', models.BooleanField(default=False, help_text='Exige CPF no pedido para liberar o cupom.')),
                ('order_types', models.JSONField(blank=True, default=list, help_text='Tipos de pedido aceitos (lista). Vazio = todos.')),
                ('combines_with_promotions', models.BooleanField(default=True, help_text='Desligado, o cupom é recusado em pedido que já tem item em promoção.')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer_groups', models.ManyToManyField(blank=True, help_text='Vazio = todos os grupos.', related_name='coupons', to='customers.customergroup')),
                ('customers', models.ManyToManyField(blank=True, help_text='Vazio = todos os clientes.', related_name='coupons', to='customers.customer')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.restaurant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.CharField(blank=True, db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.branch')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='promotions.coupon')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to='customers.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to='orders.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.restaurant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_enabled', models.BooleanField(db_index=True, default=True, help_text='Interruptor manual. Desligado, nenhuma regra da tabela vale.')),
                ('starts_at', models.DateTimeField(blank=True, help_text='Vazio = vale desde sempre.', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Vazio = não expira.', null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.restaurant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=140)),
                ('position', models.PositiveIntegerField(db_index=True, default=1)),
                ('target_type', models.CharField(choices=[('products', 'Produtos escolhidos'), ('categories', 'Categorias'), ('sectors', 'Setores'), ('all', 'Todo o cardápio')], default='products', max_length=16)),
                ('discount_kind', models.CharField(choices=[('percent', 'Percentual sobre o preço'), ('amount', 'Valor em reais abatido'), ('fixed', 'Preço fixo')], default='percent', max_length=12)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.branch')),
                ('categories', models.ManyToManyField(blank=True, related_name='promotions', to='menu.productcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.restaurant')),
                ('sectors', models.ManyToManyField(blank=True, related_name='promotions', to='restaurants.tablesector')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='promotions.discounttable')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('promotional_price', models.DecimalField(blank=True, decimal_places=2, help_text='O "por". Vazio, aplica o desconto da regra sobre o preço cadastrado.', max_digits=12, null=True)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='O "de" exibido riscado. Vazio, exibe o preço cadastrado.', max_digits=12, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_links', to='menu.product')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='promotions.promotion')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='restaurants.restaurant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='promotions', through='promotions.PromotionProduct', to='menu.product'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['account', 'is_enabled'], name='promotions__account_65666c_idx'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('account', 'code'), name='unique_coupon_code_per_account'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['coupon', 'customer'], name='promotions__coupon__52e524_idx'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['coupon', 'document'], name='promotions__coupon__dc09e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='couponredemption',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('coupon', 'order'), name='unique_coupon_redemption_per_order'),
        ),
        migrations.AddIndex(
            model_name='discounttable',
            index=models.Index(fields=['account', 'is_enabled'], name='promotions__account_2be225_idx'),
        ),
        migrations.AddConstraint(
            model_name='discounttable',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('account', 'name'), name='unique_discount_table_per_account'),
        ),
        migrations.AddConstraint(
            model_name='promotionproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('promotion', 'product'), name='unique_product_per_promotion'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['table', 'is_enabled'], name='promotions__table_i_72a22e_idx'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('table', 'position'), name='unique_promotion_position_per_table'),
        ),
    ]
