# Generated by Django 5.1.15 on 2026-08-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_account_admin',
            field=models.BooleanField(default=False),
        ),
    ]
