# Generated by Django 5.1.15 on 2026-08-27 17:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_focus_nfe_configs(apps, schema_editor):
    Account = apps.get_model("accounts", "Account")
    FocusNfeConfig = apps.get_model("accounts", "FocusNfeConfig")
    defaults = {
        "master_token": getattr(settings, "FOCUS_NFE_MASTER_TOKEN", ""),
        "production_url": getattr(settings, "FOCUS_NFE_PRODUCTION_URL", ""),
        "homologation_url": getattr(settings, "FOCUS_NFE_HOMOLOGATION_URL", ""),
        "timeout_seconds": getattr(settings, "FOCUS_NFE_TIMEOUT_SECONDS", 30),
        "auto_sync": getattr(settings, "FOCUS_NFE_AUTO_SYNC", True),
        "company_dry_run": getattr(settings, "FOCUS_NFE_COMPANY_DRY_RUN", False),
        "webhook_url": getattr(settings, "FOCUS_NFE_WEBHOOK_URL", ""),
        "webhook_authorization": getattr(settings, "FOCUS_NFE_WEBHOOK_AUTHORIZATION", ""),
        "webhook_authorization_header": getattr(
            settings,
            "FOCUS_NFE_WEBHOOK_AUTHORIZATION_HEADER",
            "Authorization",
        ),
    }
    FocusNfeConfig.objects.bulk_create(
        [FocusNfeConfig(account_id=account_id, **defaults) for account_id in Account.objects.values_list("id", flat=True)],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_is_account_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusNfeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master_token', models.CharField(blank=True, max_length=255)),
                ('production_url', models.URLField(blank=True)),
                ('homologation_url', models.URLField(blank=True)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=30)),
                ('auto_sync', models.BooleanField(default=True)),
                ('company_dry_run', models.BooleanField(default=False)),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_authorization', models.CharField(blank=True, max_length=255)),
                ('webhook_authorization_header', models.CharField(blank=True, default='Authorization', max_length=120)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='focus_nfe_config', to='accounts.account')),
            ],
            options={
                'verbose_name': 'configuracao Focus NFe',
                'verbose_name_plural': 'configuracoes Focus NFe',
            },
        ),
        migrations.RunPython(seed_focus_nfe_configs, migrations.RunPython.noop),
    ]
