# Generated by Django 5.1.15 on 2026-07-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auth_user_email_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['module', 'sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='permission',
            name='group',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='permission',
            name='module',
            field=models.CharField(default='base', max_length=40),
        ),
        migrations.AddField(
            model_name='permission',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
