# Generated by Django 5.1.15 on 2026-07-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_permission_options_permission_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='max_restaurants',
            field=models.PositiveIntegerField(default=0, help_text='Máximo de restaurantes da conta (0 = ilimitado).'),
        ),
        migrations.AddField(
            model_name='account',
            name='max_users',
            field=models.PositiveIntegerField(default=0, help_text='Máximo de usuários da conta (0 = ilimitado).'),
        ),
    ]
