# Generated by Django 5.1.15 on 2026-09-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_seed_storefront_role_and_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='local_fiscal_allowed',
            field=models.BooleanField(default=False, help_text='Autoriza esta conta a emitir NFC-e no proprio terminal. Cada loja ainda precisa ser habilitada na configuracao fiscal.'),
        ),
    ]
