# Generated by Django 5.1.15 on 2026-07-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_kdscolumn'),
        ('sla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelevelagreement',
            name='columns',
            field=models.ManyToManyField(blank=True, related_name='slas', to='kitchen.kdscolumn'),
        ),
        migrations.AddField(
            model_name='servicelevelagreement',
            name='stations',
            field=models.ManyToManyField(blank=True, related_name='slas', to='kitchen.kdsstation'),
        ),
    ]
