# Generated by Django 5.1.15 on 2026-08-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalconfig',
            name='provider_token',
            field=models.CharField(blank=True, help_text='Credencial/token do integrador fiscal (ex.: Focus NFe).', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='emission_type',
            field=models.CharField(choices=[('1', 'Normal'), ('9', 'Contingencia offline')], default='1', help_text='tpEmis da chave de acesso.', max_length=1),
        ),
    ]
