# Generated by Django 5.1.15 on 2026-08-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalconfig',
            name='focus_certificate_base64',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='focus_certificate_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='focus_company_id',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='focus_remote_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='focus_sync_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='focus_sync_status',
            field=models.CharField(choices=[('not_configured', 'Nao configurado'), ('pending', 'Aguardando sincronizacao'), ('synced', 'Sincronizado'), ('error', 'Erro de sincronizacao')], default='not_configured', max_length=24),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='focus_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='focus_token_homologation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='focus_token_production',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='provider_reference',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='cest',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='cofins_cst',
            field=models.CharField(default='49', max_length=2),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='cofins_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='pis_cst',
            field=models.CharField(default='49', max_length=2),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='pis_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='fiscalconfig',
            name='provider',
            field=models.CharField(choices=[('manual', 'Manual (sem transmissao)'), ('focus_nfe', 'Focus NFe')], default='manual', help_text='Provedor de emissao.', max_length=40),
        ),
    ]
