# Generated by Django 5.1.15 on 2026-09-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalconfig',
            name='certificate_cnpj',
            field=models.CharField(blank=True, help_text='CNPJ extraído do certificado A1.', max_length=18),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Arquivo .pfx ou .p12 do certificado A1.', null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='certificate_name',
            field=models.CharField(blank=True, help_text='Titular extraído do certificado A1.', max_length=255),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='certificate_password',
            field=models.CharField(blank=True, help_text='Senha do certificado A1.', max_length=255),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='certificate_valid_until',
            field=models.DateTimeField(blank=True, help_text='Validade do certificado A1.', null=True),
        ),
    ]
