# Generated by Django 5.1.15 on 2026-08-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_fiscalconfig_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalconfig',
            name='strict_fiscal_profile',
            field=models.BooleanField(default=False, help_text='Recusar a emissao quando o perfil fiscal de algum item estiver incompleto, em vez de completar com valores padrao.'),
        ),
    ]
