# Generated by Django 5.1.15 on 2026-09-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_fiscalconfig_strict_fiscal_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalconfig',
            name='local_fiscal_contingency',
            field=models.BooleanField(default=False, help_text='O terminal pode emitir em contingencia (tpEmis=9) quando nao alcancar o autorizador. Exige a emissao local ligada.'),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='local_fiscal_enabled',
            field=models.BooleanField(default=False, help_text='O terminal emite a NFC-e localmente, sem passar pelo backend.'),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='local_fiscal_url',
            field=models.CharField(blank=True, help_text='Onde o Comunicador escuta no terminal (padrao 127.0.0.1:8090).', max_length=255),
        ),
    ]
