# Generated by Django 5.1.15 on 2026-09-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_fiscalconfig_certificate_cnpj_and_more'),
        ('invoices', '0008_fiscalconfig_local_fiscal_contingency_and_more'),
    ]

    operations = [
    ]
