# Generated by Django 5.1.15 on 2026-09-30 21:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_local_fiscal_allowed'),
        ('invoices', '0010_unifica_certificado_focus'),
        ('restaurants', '0009_campos_adicionais_e_codigo_do_operador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fiscalprofile',
            name='unique_fiscal_profile_by_account',
        ),
        migrations.AddConstraint(
            model_name='fiscalprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('account', 'name'), name='unique_fiscal_profile_by_account'),
        ),
    ]
