# Generated by Django 5.1.15 on 2026-10-01 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_local_fiscal_allowed'),
        ('invoices', '0011_perfil_fiscal_nome_unico_so_entre_ativos'),
        ('restaurants', '0009_campos_adicionais_e_codigo_do_operador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fiscalconfig',
            name='unique_fiscal_config_by_branch',
        ),
        migrations.AddConstraint(
            model_name='fiscalconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('branch',), name='unique_fiscal_config_by_branch'),
        ),
    ]
