# Generated by Django 5.1.15 on 2026-08-29 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


FINAL_STATUSES = ("closed", "closed_with_difference", "cancelled")


def reconcile_duplicate_sessions(apps, schema_editor):
    """Encerra sessoes duplicadas antes de o indice unico passar a existir.

    O servico ja recusava uma segunda sessao por caixa, mas a checagem era
    "consulta e depois cria" — duas aberturas simultaneas podiam escapar. Numa
    base com esse residuo, `AddConstraint` falharia no meio do deploy. Aqui a
    mais recente e mantida (e a que o operador esta usando) e as anteriores
    ficam `cancelled`, com o motivo gravado em `notes` para a auditoria saber
    que foi a migracao, e nao alguem, que as encerrou.
    """
    CashRegister = apps.get_model("payments", "CashRegister")
    active = CashRegister.objects.exclude(status__in=FINAL_STATUSES).filter(
        deleted_at__isnull=True, cash_station__isnull=False
    )
    seen = set()
    stale = []
    for session in active.order_by("cash_station_id", "-opened_at").only(
        "id", "cash_station_id", "notes"
    ):
        if session.cash_station_id in seen:
            stale.append(session.pk)
        else:
            seen.add(session.cash_station_id)
    for pk in stale:
        CashRegister.objects.filter(pk=pk).update(
            status="cancelled",
            notes=(
                "Sessao duplicada encerrada automaticamente: o caixa passou a "
                "aceitar apenas uma sessao aberta por vez."
            ),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_seed_system_roles'),
        ('payments', '0001_initial'),
        ('restaurants', '0003_hash_plain_cash_action_passwords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='closed_terminal_label',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='opened_terminal_label',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.CreateModel(
            name='PdvTerminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('installation_id', models.CharField(db_index=True, help_text='UUID da instalacao, gerado e persistido pelo proprio terminal.', max_length=120)),
                ('name', models.CharField(blank=True, help_text='Nome amigavel, ex.: "Balcao 01".', max_length=120)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('web', 'Navegador'), ('mobile', 'Aplicativo')], default='desktop', max_length=16)),
                ('role', models.CharField(choices=[('principal', 'Caixa Principal'), ('secondary', 'Caixa Secundario'), ('web', 'Navegador')], default='secondary', max_length=16)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pdv_terminals', to='restaurants.restaurant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'installation_id'],
            },
        ),
        migrations.AddField(
            model_name='cashregister',
            name='closed_terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_registers_closed', to='payments.pdvterminal'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='opened_terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_registers_opened', to='payments.pdvterminal'),
        ),
        migrations.RunPython(
            reconcile_duplicate_sessions, migrations.RunPython.noop, elidable=True
        ),
        migrations.AddConstraint(
            model_name='cashregister',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('status__in', ('closed', 'closed_with_difference', 'cancelled')), _negated=True)), fields=('cash_station',), name='unique_active_session_per_cash_station'),
        ),
        migrations.AddConstraint(
            model_name='pdvterminal',
            constraint=models.UniqueConstraint(fields=('account', 'installation_id'), name='unique_pdv_terminal_installation_by_account'),
        ),
    ]
