# Generated by Django 5.1.15 on 2026-07-22 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovement',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements_authorized', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='destination',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='status',
            field=models.CharField(db_index=True, default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='approval_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_registers_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='device_identifier',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='opening_is_initial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='pending_operation',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='station',
            field=models.CharField(db_index=True, default='PDV principal', max_length=120),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='cash_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='payments.cashregister'),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='movement_type',
            field=models.CharField(choices=[('opening', 'Opening'), ('sale', 'Sale'), ('withdrawal', 'Withdrawal'), ('supply', 'Supply'), ('closing', 'Closing'), ('adjustment', 'Adjustment'), ('refund', 'Estorno em dinheiro')], db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='status',
            field=models.CharField(choices=[('pending_opening', 'Aguardando abertura'), ('open', 'Open'), ('blocked', 'Bloqueado'), ('pending_manager_approval', 'Aguardando aprovação gerencial'), ('pending_closing', 'Aguardando fechamento'), ('closed', 'Closed'), ('closed_with_difference', 'Fechado com divergência'), ('cancelled', 'Cancelado')], db_index=True, default='open', max_length=32),
        ),
    ]
