# Generated by Django 5.1.15 on 2026-10-01 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_local_fiscal_allowed'),
        ('payments', '0002_pdv_terminal_and_session_exclusivity'),
        ('restaurants', '0009_campos_adicionais_e_codigo_do_operador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cashstation',
            name='unique_cash_station_code_by_restaurant',
        ),
        migrations.RemoveConstraint(
            model_name='paymentmethod',
            name='unique_payment_method_by_branch',
        ),
        migrations.AddConstraint(
            model_name='cashstation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('restaurant', 'code'), name='unique_cash_station_code_by_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('branch', 'name'), name='unique_payment_method_by_branch'),
        ),
    ]
