# Generated by Django 5.1.15 on 2026-09-17 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_seed_storefront_role_and_permissions'),
        ('restaurants', '0006_restaurant_commands_per_table_and_grace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pair_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('node_type', models.CharField(choices=[('LOCAL', 'Servidor da loja'), ('CLOUD', 'Servidor da nuvem')], db_index=True, max_length=8)),
                ('environment', models.CharField(choices=[('development', 'Development')], default='development', max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('endpoint', models.URLField(blank=True, help_text='URL WSS que o nó local procura.')),
                ('allowed_ip', models.GenericIPAddressField(blank=True, help_text='Restrição adicional. Nunca é a autenticação principal.', null=True)),
                ('credential_hash', models.CharField(blank=True, max_length=128)),
                ('credential_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('encryption_key_id', models.CharField(blank=True, max_length=64)),
                ('secret_fingerprint', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando primeiro handshake'), ('ACTIVE', 'Ativo'), ('OFFLINE', 'Sem conexão'), ('BLOCKED', 'Bloqueado'), ('REVOKED', 'Revogado')], default='PENDING', max_length=10)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('schema_version', models.PositiveIntegerField(default=0)),
                ('protocol_version', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_cursor', models.BigIntegerField(default=0)),
                ('last_received_cursor', models.BigIntegerField(default=0)),
                ('sequence_counter', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_self', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_nodes', to='accounts.account')),
                ('peer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peer_of', to='synchronization.syncnode')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sync_nodes', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Nó de sincronização',
                'verbose_name_plural': 'Nós de sincronização',
                'ordering': ['account', 'node_type', 'name'],
                'permissions': [('can_start_full_sync', 'Pode iniciar sincronização completa'), ('can_provision_node', 'Pode gerar credenciais de nó'), ('can_revoke_node', 'Pode revogar um nó')],
            },
        ),
        migrations.CreateModel(
            name='SyncEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('direction', models.CharField(choices=[('INBOUND', 'Recebido'), ('OUTBOUND', 'Enviado')], db_index=True, max_length=8)),
                ('sequence', models.BigIntegerField()),
                ('entity_type', models.CharField(db_index=True, max_length=80)),
                ('entity_id', models.CharField(db_index=True, max_length=64)),
                ('operation', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('UPSERT', 'Upsert'), ('SNAPSHOT', 'Snapshot')], max_length=10)),
                ('entity_version', models.BigIntegerField(default=1)),
                ('protocol_version', models.PositiveIntegerField(default=1)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('payload', models.JSONField(default=dict)),
                ('payload_checksum', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Na fila'), ('PROCESSING', 'Em processamento'), ('SENT', 'Enviado, sem confirmação'), ('RECEIVED', 'Recebido pelo destino'), ('APPLIED', 'Aplicado no destino'), ('ACKNOWLEDGED', 'Confirmado na origem'), ('FAILED', 'Falhou, vai tentar de novo'), ('DEAD', 'Desistiu; exige reprocessamento manual')], default='PENDING', max_length=14)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_events', to='accounts.account')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events_sent', to='synchronization.syncnode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events_received', to='synchronization.syncnode')),
            ],
            options={
                'verbose_name': 'Evento de sincronização',
                'verbose_name_plural': 'Eventos de sincronização',
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(db_index=True, max_length=80)),
                ('entity_id', models.CharField(db_index=True, max_length=64)),
                ('local_version', models.BigIntegerField(default=0)),
                ('remote_version', models.BigIntegerField(default=0)),
                ('local_payload', models.JSONField(blank=True, default=dict)),
                ('remote_payload', models.JSONField(blank=True, default=dict)),
                ('resolution', models.CharField(choices=[('CLOUD_WINS', 'Nuvem vence'), ('LOCAL_WINS', 'Loja vence'), ('LAST_VERSION', 'Maior versão vence'), ('MANUAL', 'Revisão manual'), ('IGNORED', 'Ignorado')], default='MANUAL', max_length=14)),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('RESOLVED', 'Resolvido'), ('IGNORED', 'Ignorado')], default='OPEN', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_conflicts', to='accounts.account')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts', to='synchronization.syncevent')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflicts_as_source', to='synchronization.syncnode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflicts_as_target', to='synchronization.syncnode')),
            ],
            options={
                'verbose_name': 'Conflito de sincronização',
                'verbose_name_plural': 'Conflitos de sincronização',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_type', models.CharField(choices=[('BOOTSTRAP', 'Dados essenciais'), ('FULL', 'Tudo'), ('INCREMENTAL', 'Incremental')], max_length=12)),
                ('status', models.CharField(choices=[('PENDING', 'Na fila'), ('PREPARING', 'Preparando'), ('RUNNING', 'Enviando'), ('VALIDATING', 'Validando'), ('COMPLETED', 'Concluída'), ('FAILED', 'Falhou'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=12)),
                ('snapshot_cursor', models.BigIntegerField(default=0)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('current_entity', models.CharField(blank=True, max_length=80)),
                ('total_entities', models.PositiveIntegerField(default=0)),
                ('processed_entities', models.PositiveIntegerField(default=0)),
                ('total_records', models.BigIntegerField(default=0)),
                ('processed_records', models.BigIntegerField(default=0)),
                ('failed_records', models.BigIntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('processed_bytes', models.BigIntegerField(default=0)),
                ('initiated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_runs', to='accounts.account')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs_as_source', to='synchronization.syncnode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs_as_target', to='synchronization.syncnode')),
            ],
            options={
                'verbose_name': 'Carga de sincronização',
                'verbose_name_plural': 'Cargas de sincronização',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='syncevent',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='synchronization.syncrun'),
        ),
        migrations.AddIndex(
            model_name='syncnode',
            index=models.Index(fields=['account', 'status'], name='synchroniza_account_a77e96_idx'),
        ),
        migrations.AddIndex(
            model_name='syncnode',
            index=models.Index(fields=['node_type', 'is_active'], name='synchroniza_node_ty_7b8324_idx'),
        ),
        migrations.AddConstraint(
            model_name='syncnode',
            constraint=models.UniqueConstraint(fields=('pair_id', 'node_type'), name='sync_unique_node_type_per_pair'),
        ),
        migrations.AddIndex(
            model_name='syncconflict',
            index=models.Index(fields=['account', 'status'], name='synchroniza_account_91b7e4_idx'),
        ),
        migrations.AddIndex(
            model_name='syncconflict',
            index=models.Index(fields=['entity_type', 'entity_id'], name='synchroniza_entity__12c394_idx'),
        ),
        migrations.AddIndex(
            model_name='syncrun',
            index=models.Index(fields=['account', 'status'], name='synchroniza_account_d0ad60_idx'),
        ),
        migrations.AddIndex(
            model_name='syncrun',
            index=models.Index(fields=['target_node', 'status'], name='synchroniza_target__a3809e_idx'),
        ),
        migrations.AddIndex(
            model_name='syncevent',
            index=models.Index(fields=['account', 'status', 'created_at'], name='synchroniza_account_7e4ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='syncevent',
            index=models.Index(fields=['target_node', 'status'], name='synchroniza_target__03ac95_idx'),
        ),
        migrations.AddIndex(
            model_name='syncevent',
            index=models.Index(fields=['entity_type', 'entity_id'], name='synchroniza_entity__8cdad2_idx'),
        ),
        migrations.AddIndex(
            model_name='syncevent',
            index=models.Index(fields=['status', 'next_attempt_at'], name='synchroniza_status_27a2ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='syncevent',
            constraint=models.UniqueConstraint(fields=('source_node', 'direction', 'sequence'), name='sync_unique_sequence_per_source'),
        ),
    ]
