# Generated by Django 5.1.15 on 2026-09-17 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_seed_storefront_role_and_permissions'),
        ('synchronization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncFileTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(db_index=True, max_length=80)),
                ('entity_id', models.CharField(db_index=True, max_length=64)),
                ('field_name', models.CharField(max_length=80)),
                ('storage_path', models.CharField(max_length=500)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('total_bytes', models.BigIntegerField()),
                ('received_bytes', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando o primeiro pedaço'), ('RECEIVING', 'Recebendo'), ('VALIDATING', 'Conferindo checksum'), ('COMPLETED', 'Concluída'), ('FAILED', 'Falhou')], default='PENDING', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('temp_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_transfers', to='accounts.account')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_sent', to='synchronization.syncnode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_received', to='synchronization.syncnode')),
            ],
            options={
                'verbose_name': 'Transferência de arquivo',
                'verbose_name_plural': 'Transferências de arquivo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'status'], name='synchroniza_account_96618b_idx'), models.Index(fields=['entity_type', 'entity_id'], name='synchroniza_entity__159e61_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'RECEIVING', 'VALIDATING'])), fields=('target_node', 'storage_path', 'checksum'), name='sync_unique_open_transfer')],
            },
        ),
    ]
