# Generated by Django 5.1.15 on 2026-09-17 15:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronization', '0002_syncfiletransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncDirty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_name', models.CharField(db_index=True, max_length=120)),
                ('row_id', models.CharField(db_index=True, max_length=64)),
                ('operation', models.CharField(max_length=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_dirty', to='synchronization.syncevent')),
            ],
            options={
                'verbose_name': 'Marca de alteração fora do ORM',
                'verbose_name_plural': 'Marcas de alteração fora do ORM',
                'ordering': ['changed_at'],
                'indexes': [models.Index(fields=['processed_at', 'changed_at'], name='synchroniza_process_f700cb_idx'), models.Index(fields=['table_name', 'row_id'], name='synchroniza_table_n_4070db_idx')],
            },
        ),
    ]
