# Generated by Django 5.1.15 on 2026-09-17 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronization', '0003_syncdirty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncnode',
            name='peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peers', to='synchronization.syncnode'),
        ),
    ]
