"""Índices PARCIAIS para as duas consultas do caminho quente da fila.

A fila viva é uma fatia minúscula da tabela: o normal é quase tudo estar
ACKNOWLEDGED ou APPLIED. Um índice completo carregaria milhões de linhas
terminais para responder sobre as poucas abertas, e seria reescrito a cada
evento que chega ao fim. Estes só indexam o que a consulta procura.

## ANTES DE RODAR NUMA NUVEM COM FILA GRANDE

`CREATE INDEX` comum trava ESCRITA na tabela enquanto constrói. Em
`synchronization_syncevent` isso significa toda loja parando de entregar venda
até terminar — e o tamanho dessa tabela cresce com o movimento, então o
problema aparece justamente no dia de mais movimento.

Com a tabela grande, crie os dois à mão primeiro e só depois marque a migration
como aplicada:

    CREATE INDEX CONCURRENTLY sync_saida_viva_idx
      ON synchronization_syncevent (target_node_id, sequence)
      WHERE direction = 'OUTBOUND' AND status IN ('PENDING', 'FAILED');

    CREATE INDEX CONCURRENTLY sync_entrada_viva_idx
      ON synchronization_syncevent (target_node_id, sequence)
      WHERE direction = 'INBOUND' AND status IN ('RECEIVED', 'FAILED');

    manage.py migrate synchronization 0006 --fake

`CONCURRENTLY` não pode rodar dentro de transação, e é por isso que ele não
está nesta migration: o Django envolve migration em transação, e uma versão
`atomic = False` com `AddIndexConcurrently` quebraria a suíte inteira, que roda
em SQLite.
"""
# Generated by Django 5.1.15 on 2026-09-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_local_fiscal_allowed'),
        ('synchronization', '0005_funde_nos_proprios_duplicados'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='syncevent',
            index=models.Index(condition=models.Q(('direction', 'OUTBOUND'), ('status__in', ['PENDING', 'FAILED'])), fields=['target_node', 'sequence'], name='sync_saida_viva_idx'),
        ),
        migrations.AddIndex(
            model_name='syncevent',
            index=models.Index(condition=models.Q(('direction', 'INBOUND'), ('status__in', ['RECEIVED', 'FAILED'])), fields=['target_node', 'sequence'], name='sync_entrada_viva_idx'),
        ),
    ]
