"""Índices PARCIAIS para as duas consultas do caminho quente da fila.

A fila viva é uma fatia minúscula da tabela: o normal é quase tudo estar
ACKNOWLEDGED ou APPLIED. Um índice completo carregaria milhões de linhas
terminais para responder sobre as poucas abertas, e seria reescrito a cada
evento que chega ao fim. Estes só indexam o que a consulta procura.
"""
# Generated by Django 5.1.15 on 2026-09-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_local_fiscal_allowed'),
        ('synchronization', '0005_funde_nos_proprios_duplicados'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='syncevent',
            index=models.Index(condition=models.Q(('direction', 'OUTBOUND'), ('status__in', ['PENDING', 'FAILED'])), fields=['target_node', 'sequence'], name='sync_saida_viva_idx'),
        ),
        migrations.AddIndex(
            model_name='syncevent',
            index=models.Index(condition=models.Q(('direction', 'INBOUND'), ('status__in', ['RECEIVED', 'FAILED'])), fields=['target_node', 'sequence'], name='sync_entrada_viva_idx'),
        ),
    ]
