"""Abre `production` como valor de `SyncNode.environment`.

Só mexe em `choices`, que vive no Python: nenhuma linha muda e nenhuma
coluna é reescrita. Mover as fichas existentes é trabalho de
`manage.py sync_set_environment`, e precisa ser deliberado — o ambiente
faz parte da identidade do nó, e trocá-lo sozinho derruba o HELLO.
"""
# Generated by Django 5.1.15 on 2026-09-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronization', '0007_bilhete_de_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncnode',
            name='environment',
            field=models.CharField(choices=[('development', 'Development'), ('production', 'Production')], default='development', max_length=16),
        ),
    ]
