# Generated by Django 5.1.15 on 2026-09-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronization', '0009_reserva_faixa_de_id_de_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncnode',
            name='offline_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
